var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};$jscomp.polyfill=function(a,b,d,c){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,c):$jscomp.polyfillUnisolated(a,b,d,c))};
$jscomp.polyfillUnisolated=function(a,b,d,c){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];if(!(f in d))return;d=d[f]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,c){var f=a.split(".");a=1===f.length;c=f[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<f.length-1;g++){var e=f[g];if(!(e in c))return;c=c[e]}f=f[f.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?c[f]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==d&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=
$jscomp.propertyToPolyfillSymbol[f],$jscomp.defineProperty(c,f,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var d=a.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(d.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(d){return{value:d,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var c=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(c);if(!c.done)return this.context_.stop_(),c;var f=c.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(c){return a.next(c)}function d(c){return a.throw(c)}return new Promise(function(c,f){function g(e){e.done?c(e.value):Promise.resolve(e.value).then(b,d).then(g,f)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(f,g){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,c=function(f){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(f||"")+"_"+d++,f)};return c},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var c=$jscomp.global[b[d]];"function"===typeof c&&"function"!=typeof c.prototype[a]&&$jscomp.defineProperty(c.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(e){return e instanceof f?e:new f(function(h,k){h(e)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(e){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(e)};
var c=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(e){c(e,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var e=this.batch_;this.batch_=[];for(var h=0;h<e.length;++h){var k=e[h];e[h]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(e){this.asyncExecuteFunction(function(){throw e;})};var f=function(e){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var h=this.createResolveAndReject_();
try{e(h.resolve,h.reject)}catch(k){h.reject(k)}};f.prototype.createResolveAndReject_=function(){function e(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:e(this.resolveTo_),reject:e(this.reject_)}};f.prototype.resolveTo_=function(e){if(e===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof f)this.settleSameAsPromise_(e);else{a:switch(typeof e){case "object":var h=null!=e;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(e):
this.fulfill_(e)}};f.prototype.resolveToNonPromiseObj_=function(e){var h=void 0;try{h=e.then}catch(k){this.reject_(k);return}"function"==typeof h?this.settleSameAsThenable_(h,e):this.fulfill_(e)};f.prototype.reject_=function(e){this.settle_(2,e)};f.prototype.fulfill_=function(e){this.settle_(1,e)};f.prototype.settle_=function(e,h){if(0!=this.state_)throw Error("Cannot settle("+e+", "+h+"): Promise already settled in state"+this.state_);this.state_=e;this.result_=h;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};f.prototype.scheduleUnhandledRejectionCheck_=function(){var e=this;c(function(){if(e.notifyUnhandledRejection_()){var h=$jscomp.global.console;"undefined"!==typeof h&&h.error(e.result_)}},1)};f.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var e=$jscomp.global.CustomEvent,h=$jscomp.global.Event,k=$jscomp.global.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof e?e=new e("unhandledrejection",{cancelable:!0}):
"function"===typeof h?e=new h("unhandledrejection",{cancelable:!0}):(e=$jscomp.global.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.result_;return k(e)};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var e=0;e<this.onSettledCallbacks_.length;++e)g.asyncExecute(this.onSettledCallbacks_[e]);this.onSettledCallbacks_=null}};var g=new b;f.prototype.settleSameAsPromise_=function(e){var h=this.createResolveAndReject_();
e.callWhenSettled_(h.resolve,h.reject)};f.prototype.settleSameAsThenable_=function(e,h){var k=this.createResolveAndReject_();try{e.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};f.prototype.then=function(e,h){function k(q,p){return"function"==typeof q?function(r){try{l(q(r))}catch(t){m(t)}}:p}var l,m,n=new f(function(q,p){l=q;m=p});this.callWhenSettled_(k(e,l),k(h,m));return n};f.prototype.catch=function(e){return this.then(void 0,e)};f.prototype.callWhenSettled_=function(e,h){function k(){switch(l.state_){case 1:e(l.result_);
break;case 2:h(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?g.asyncExecute(k):this.onSettledCallbacks_.push(k);this.isRejectionHandled_=!0};f.resolve=d;f.reject=function(e){return new f(function(h,k){k(e)})};f.race=function(e){return new f(function(h,k){for(var l=$jscomp.makeIterator(e),m=l.next();!m.done;m=l.next())d(m.value).callWhenSettled_(h,k)})};f.all=function(e){var h=$jscomp.makeIterator(e),k=h.next();return k.done?d([]):new f(function(l,
m){function n(r){return function(t){q[r]=t;p--;0==p&&l(q)}}var q=[],p=0;do q.push(void 0),p++,d(k.value).callWhenSettled_(n(q.length-1),m),k=h.next();while(!k.done)})};return f},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(b,d,c){d=null!=d?d:function(h){return h};var f=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var e=0;!(g=b.next()).done;)f.push(d.call(c,g.value,e++))}else for(g=b.length,e=0;e<g;e++)f.push(d.call(c,b[e],e));return f}},"es6","es3");
function Explosion(){var a,b,d,c,f,g,e,h,k,l;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){switch(m.nextAddress){case 1:b=[];d=Scene.querySelectorAll('[id^="Reagent"]');c=EXPLOSION_SCALE/-2;f=0;g=$jscomp.makeIterator(d);for(e=g.next();!e.done;e=g.next())a=e.value,f++%2?b.push(a):a.setAttribute("visible","false");h=$jscomp.makeIterator(GlassWare);for(e=h.next();!e.done;e=h.next())a=e.value,b.push(a.Handle);b.push(AnalyteHandle);b.push(Bunsen.Handle);b.push(Heater.Handle);b.push(Lighter.Handle);
b.push(Rack);b.push(Spatula);b.push(Trash);b.push(Workbench.querySelector("#Book"));b.push(Workbench.querySelector("#Paper"));b.push(Workbench.querySelector("#PhotoFrameSmell"));Boil(WaterBath,!1);CentrifugeTime(0,!1);Tv.Video.pause();k=$jscomp.makeIterator(b);for(e=k.next();!e.done;e=k.next())a=e.value,a.removeAttribute("animation__1"),a.removeAttribute("animation__2"),a.setAttribute("animation__1","dur: "+EXPLOSION_DUR+"; property: position; to: "+(c+Math.random()*EXPLOSION_SCALE)+" "+(c+Math.random()*
EXPLOSION_SCALE)+" "+(c+Math.random()*EXPLOSION_SCALE)),a.setAttribute("animation__2","dur: "+EXPLOSION_DUR+"; property: rotation; to: "+360*Math.random()+" "+360*Math.random()+" "+360*Math.random());StopSound("SND_BoilWater");Scene.querySelector("#FlameExplosion").setAttribute("particle-system","enabled: true");PlaySound("SND_Explosion");return m.yield(Sleep(EXPLOSION_DUR),2);case 2:l=$jscomp.makeIterator(b);for(e=l.next();!e.done;e=l.next())a=e.value,a.setAttribute("visible","false");return m.yield(Sleep(2E3),
3);case 3:return PlaySound("SND_Burn"),m.yield(Sleep(2E3),4);case 4:return Speak(Msg.SsExplosion),m.yield(Sleep(1E4),5);case 5:location.reload(!0),m.jumpToEnd()}})}
function ScBathClick(){if(!AnimRunning)if(GlassReady.Obj)if(GlassReady.Obj.Bath)if(GlassIsEmpty(GlassReady.Obj))Speak(Msg.SsBathGlassEmpty);else{var a;for(a=0;WaterBath.DockHole[a];++a);WaterBath.DockHole[a]=GlassReady.Obj;var b=GlassReady.Handle,d=b.getAttribute("position");a=PositionToLocal(Rack,WaterBath.Handle.querySelector("#StandHole"+(a+1)));b.removeAttribute("animation__DockRack");AnimRunning=!0;b.setAttribute("animation__DockRack","dur: 500; property: position ; from: "+d.x+" "+d.y+" "+d.z+
"; to: "+a.x+" "+d.y+" "+a.z)}else Speak(Msg.SsCantPutInBath);else Speak(Msg.SsSelectGlassware)}
function ScDropperClick(a){if(!AnimRunning)if(a.Dropper)if(a.Burning)Speak(Msg.SsCantBurning);else{var b=GlassReady.Obj;if(GlassIsEmpty(b)){if(!a.Water){Speak(Msg.SsDropperNothing);return}if(a.Type===GLASS_TYPE_TESTTUBE&&a.PaperID){Speak(Msg.SsDropperPaper1);return}}else if(a.Type===GLASS_TYPE_TESTTUBE&&a.PaperID)if(a.PaperID===REA_ID_UNIVIND){if(b.AnaID||b.ReaNum){Speak(Msg.SsDropperInd);return}}else if(b.AnaID||1<b.ReaNum){Speak(Msg.SsDropperPaper2);return}if(GlassWater(a)||GlassSameSubst(b,a)||
GlassIsClean(b)){RingTest=!1;switch(a.Type){case GLASS_TYPE_BEAKER:var d=.05;var c=.057;var f=.005;break;case GLASS_TYPE_CURCIBLE:case GLASS_TYPE_WATCHGLASS:d=0;c=.05;f=.02;break;case GLASS_TYPE_TESTTUBE:d=.19,c=.035,f=a.PaperID?-.18:-.15}var g=b.Handle,e=g.querySelector("#Rubber"),h=g.getAttribute("position"),k=PositionToLocal(Workbench,a.Handle);GlassTarget=a;GlassIsEmpty(b)?a="":(a="d",c=f);AnimRunning=!0;d+=h.y;c=h.y-c;g.removeAttribute("animation__1");g.removeAttribute("animation__2");e.removeAttribute("animation__1"+
a);e.removeAttribute("animation__2"+a);g.removeAttribute("animation__3");g.removeAttribute("animation__L");g.setAttribute("animation__1","dur: 500; property: position ; from: "+h.x+" "+h.y+" "+h.z+"; to: "+k.x+" "+d+" "+k.z);g.setAttribute("animation__2","delay: 500; dur: 500; property: position ; from: "+k.x+" "+d+" "+k.z+"; to: "+k.x+" "+c+" "+k.z);e.setAttribute("animation__1"+a,"delay: 1000; dur: 500; property: scale; from: 1 1 1; to: 0.5 1 1");e.setAttribute("animation__2"+a,"delay: 1600; dur: 500; property: scale; from: 0.5 1 1; to: 1 1 1");
g.setAttribute("animation__3","delay: 2100; dur: 500; property: position; ; from: "+k.x+" "+c+" "+k.z+"; to: "+k.x+" "+d+" "+k.z);g.setAttribute("animation__L","delay: 2700; dur: 500; property: position; ; from: "+k.x+" "+d+" "+k.z+"; to: "+h.x+" "+h.y+" "+h.z)}}else Speak(Msg.SsCantUseDropper)}function ScDropperUse(){GlassReady.Type===GLASS_TYPE_DROPPER?ScDropperClick(GlassReady):ScReaPipetteClick()}
function ScGlassWareClick(a,b,d){if(!AnimRunning){if(!a)if(b===GLASS_CLICK_LEAVE&&GlassReady.Obj){if(d&SCGWCLICK_TESTTUBEONLY&&GlassReady.Obj.Type!==GLASS_TYPE_TESTTUBE){Speak(Msg.SsNotUnderstand2);return}a=GlassReady.Obj}else{Speak(Msg.SsNothingToLeave);return}if(b===GLASS_CLICK_USE){switch(a.Type){case GLASS_TYPE_BEAKER:var c=Msg.SsCantUseBeaker;break;case GLASS_TYPE_CURCIBLE:c=Msg.SsCantUseCurcible;break;case GLASS_TYPE_DROPPER:ScDropperClick(GlassReady);return;case GLASS_TYPE_NICHROME:ScNichromeClick(GlassReady);
return;case GLASS_TYPE_STIRRER:ScStirrerClick(GlassReady);return;case GLASS_TYPE_TESTTUBE:c=Msg.SsCantTestTube;break;case GLASS_TYPE_WATCHGLASS:c=Msg.SsCantUseWatchGlass}Speak(c)}else if(GlassReady.Obj===Lighter&&a!==Lighter)ScLighterClick(a);else if(a.Burning)Speak(Msg.SsCantBurning);else if(GlassReady.Obj===Dropper&&a!==Dropper)ScDropperClick(a);else if(GlassReady.Obj!==Nichrome||a===Nichrome||a.Type!==GLASS_TYPE_BUNSEN&&a.Type!==GLASS_TYPE_TESTTUBE&&a.Type!==GLASS_TYPE_WATCHGLASS)if(GlassReady.Obj===
Stirrer&&a!==Stirrer)ScStirrerClick(a);else{var f=a.Handle;if(GlassReady.Handle){if(GlassReady.Handle==f&&b==GLASS_CLICK_TAKE){Speak(Msg.SsAlreadyTaken);return}if(GlassReady.Handle!=f&&b===GLASS_CLICK_LEAVE){Speak(Msg.SsNotUnderstand2);return}AnimRunning=!0;c=GlassReady.Handle.getAttribute("position");GlassReady.Handle.removeAttribute("animation__1");GlassReady.Handle.removeAttribute("animation__L");switch(GlassReady.Obj){case Dropper:GlassReady.Handle.setAttribute("animation__1","dur: 500; property: rotation; from: 0 0 0; to: 88.5 0 0");
break;case Lighter:GlassReady.Handle.setAttribute("animation__1","dur: 500; property: rotation; from: 0 0 0; to: -90 0 0")}GlassReady.Handle.setAttribute("animation__L","dur: 500; property: position; from: "+c.x+" "+c.y+" "+c.z+"; to: "+c.x+" "+GlassReady.LeaveY+" "+c.z);if(GlassReady.Handle===f){GlassReady.Handle=null;GlassReady.Obj=null;return}}else if(b==GLASS_CLICK_LEAVE){Speak(Msg.SsNothingToLeave);return}AnimRunning=!0;c=f.getAttribute("position");GlassReady.LeaveY=c.y;var g=a.PosY+(a.Type==
GLASS_TYPE_TESTTUBE?1.5:.15);f.removeAttribute("animation__L");if(a.Dock){switch(a.Dock){case Centrifuge.Handle:if(b===GLASS_CLICK_TAKE&&!Centrifuge.Open){AnimRunning=!1;return}for(b=0;6>b;++b)if(Centrifuge.DockTube[b]===a){Centrifuge.DockTube[b]=null;break}GlassReady.LeaveY=a.PosY;break;case Heater.Handle:if(!(d&SCGWCLICK_NOMOVEBATH)){b=WaterBath.Handle;d=b.getAttribute("position");var e=WaterBath.PosY+WATERBATH_MOVEUP;b.removeAttribute("animation__1");b.removeAttribute("animation__2");b.removeAttribute("animation__L");
for(var h=0;h<WaterBath.DockHole.length;++h)if(WaterBath.DockHole[h]){var k=WaterBath.DockHole[h].Handle,l=k.getAttribute("position"),m=PositionToLocal(Workbench,k),n=new THREE.Vector3(m.x,m.y+WATERBATH_MOVEDOWN,m.z);m.y+=WATERBATH_MOVEUP+WATERBATH_MOVEDOWN;m.z-=WATERBATH_MOVEZ;Workbench.object3D.localToWorld(m);Workbench.object3D.localToWorld(n);Rack.object3D.updateMatrixWorld();Rack.object3D.worldToLocal(m);Rack.object3D.worldToLocal(n);k.removeAttribute("animation__1");k.removeAttribute("animation__2");
k.removeAttribute("animation__3");k.setAttribute("animation__1","delay: 1000; dur: 500; property: position ; from: "+l.x+" "+l.y+" "+l.z+"; to: "+l.x+" "+m.y+" "+l.z);k.setAttribute("animation__2","delay: 1500; dur: 500; property: position ; from: "+l.x+" "+m.y+" "+l.z+"; to: "+m.x+" "+m.y+" "+m.z);k.setAttribute("animation__3","delay: 2000; dur: 500; property: position ; from: "+m.x+" "+m.y+" "+m.z+"; to: "+m.x+" "+n.y+" "+m.z)}b.setAttribute("animation__1","delay: 1000; dur: 500; property: position ; from: "+
d.x+" "+d.y+" "+d.z+"; to: "+d.x+" "+e+" "+d.z);b.setAttribute("animation__2","delay: 1500; dur: 500; property: position ; from: "+d.x+" "+e+" "+d.z+"; to: "+WaterBath.PosX+" "+e+" "+WaterBath.PosZ);b.setAttribute("animation__L","delay: 2000; dur: 500; property: position ; from: "+WaterBath.PosX+" "+e+" "+WaterBath.PosZ+"; to: "+WaterBath.PosX+" "+WaterBath.PosY+" "+WaterBath.PosZ);WaterBath.Dock=Heater.Handle}GlassReady.LeaveY-=.09;break;case Rack:for(h=0;h<WaterBath.DockHole.length;++h)if(WaterBath.DockHole[h]==
a){WaterBath.DockHole[h]=null;break}GlassReady.LeaveY=a.PosY}f.removeAttribute("animation__1");f.setAttribute("animation__1","dur: 500; property: position; from: "+c.x+" "+c.y+" "+c.z+"; to: "+c.x+" "+g+" "+c.z);f.setAttribute("animation__L","delay: 500; dur: 500; property: position; from: "+c.x+" "+g+" "+c.z+"; to: "+a.PosX+" "+g+" "+a.PosZ);a.Dock=null}else{f.removeAttribute("animation__1");switch(a){case Dropper:f.setAttribute("animation__1","dur: 500; property: rotation; from: 88.5 0 0; to: 0 0 0");
break;case Lighter:f.setAttribute("animation__1","dur: 500; property: rotation; from: -90 0 0; to: 0 0 0")}f.setAttribute("animation__L","dur: 500; property: position; from: "+c.x+" "+c.y+" "+c.z+"; to: "+c.x+" "+g+" "+c.z)}GlassReady.Handle=f;GlassReady.Obj=a}else ScNichromeClick(a)}}
function ScHeaterClick(){var a,b,d,c,f,g,e,h,k,l,m,n,q;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){switch(p.nextAddress){case 1:if(AnimRunning)return p.return();if(!GlassReady.Obj)return Speak(Msg.SsSelectGlassware),p.return();if(!GlassReady.Obj.Heater)return Speak(Msg.SsHeaterCantPut),p.return();if(GlassIsEmpty(GlassReady.Obj))return Speak(Msg.SsHeaterGlassEmpty),p.return();if(GlassReady.Obj.Type===GLASS_TYPE_BEAKER&&!GlassReady.Obj.Water)return Speak(Msg.SsHeaterBeakerWater),
p.return();a=2E3;b=GlassReady.Handle;d=GlassReady.Obj;c=b.getAttribute("position");f=PositionToLocal(WorkBench,Heater.Handle.querySelector("#HeaterDock"));g=new THREE.Vector3(WaterBath.PosX,WaterBath.PosY+WATERBATH_MOVEUP,WaterBath.PosZ+WATERBATH_MOVEZ);e=WaterBath.Handle;h=0;case 2:if(!(h<GlassWare.length)){p.jumpTo(4);break}if(GlassWare[h].Dock!==Heater.Handle||GlassWare[h]===WaterBath){p.jumpTo(3);break}ScGlassWareClick(d,GLASS_CLICK_LEAVE,SCGWCLICK_NOMOVEBATH);return p.yield(WaitAnimEnd(500),
6);case 6:return ScGlassWareClick(GlassWare[h],GLASS_CLICK_TAKE,SCGWCLICK_NOMOVEBATH),p.yield(WaitAnimEnd(500),7);case 7:return ScGlassWareClick(d,GLASS_CLICK_TAKE,SCGWCLICK_NOMOVEBATH),p.yield(WaitAnimEnd(500),8);case 8:a=0;BoilDelay(GlassWare[h],!1);p.jumpTo(4);break;case 3:h++;p.jumpTo(2);break;case 4:AnimRunning=!0;if(WaterBath.Dock){WaterBath.Dock=null;e.removeAttribute("animation__1");e.removeAttribute("animation__2");e.removeAttribute("animation__L");for(k=0;k<WaterBath.DockHole.length;++k)WaterBath.DockHole[k]&&
(l=WaterBath.DockHole[k].Handle,m=l.getAttribute("position"),n=PositionToLocal(Workbench,l),q=new THREE.Vector3(n.x,n.y-WATERBATH_MOVEDOWN,n.z),n.y+=WATERBATH_MOVEUP,n.z+=WATERBATH_MOVEZ,Workbench.object3D.localToWorld(n),Workbench.object3D.localToWorld(q),Rack.object3D.updateMatrixWorld(),Rack.object3D.worldToLocal(n),Rack.object3D.worldToLocal(q),l.removeAttribute("animation__1"),l.removeAttribute("animation__2"),l.removeAttribute("animation__3"),l.setAttribute("animation__1","dur: 500; property: position ; from: "+
m.x+" "+m.y+" "+m.z+"; to: "+m.x+" "+n.y+" "+m.z),l.setAttribute("animation__2","delay: 500; dur: 500; property: position ; from: "+m.x+" "+n.y+" "+m.z+"; to: "+n.x+" "+n.y+" "+n.z),l.setAttribute("animation__3","delay: 1000; dur: 500; property: position ; from: "+n.x+" "+n.y+" "+n.z+"; to: "+n.x+" "+q.y+" "+n.z));e.setAttribute("animation__1","dur: 500; property: position ; from: "+WaterBath.PosX+" "+WaterBath.PosY+" "+WaterBath.PosZ+"; to: "+WaterBath.PosX+" "+g.y+" "+WaterBath.PosZ);e.setAttribute("animation__2",
"delay: 500; dur: 500; property: position ; from: "+WaterBath.PosX+" "+g.y+" "+WaterBath.PosZ+"; to: "+g.x+" "+g.y+" "+g.z);e.setAttribute("animation__L","delay: 1000; dur: 500; property: position ; from: "+g.x+" "+g.y+" "+g.z+"; to: "+g.x+" "+(WaterBath.PosY-WATERBATH_MOVEDOWN)+" "+g.z)}b.removeAttribute("animation__DockHeater");b.setAttribute("animation__DockHeater","delay: "+a+"; dur: 500; property: position ; from: "+c.x+" "+c.y+" "+c.z+"; to: "+f.x+" "+c.y+" "+f.z);p.jumpToEnd()}})}
function ScLighterClick(a){if(!AnimRunning)if(a.Lighter)if(a.Burning)Speak(a.Type===GLASS_TYPE_BUNSEN?Msg.SsBunsenAlrOn:Msg.SsLighterBurning);else if(a.Type!==GLASS_TYPE_BUNSEN&&GlassIsEmpty(a))Speak(Msg.SsLighterNothing);else{switch(a.Type){case GLASS_TYPE_BUNSEN:if(a.Ox){ShowError(Msg.SsBunsenNoRed);return}var b=.25;var d=.22;break;case GLASS_TYPE_CURCIBLE:b=.1,d=.05}AnimRunning=!0;var c=Lighter.Handle,f=c.querySelector("#Button"),g=c.getAttribute("position"),e=PositionToLocal(Workbench,a.Handle);
GlassTarget=a;b+=e.y;d+=e.y;e.x+=.04;f.removeAttribute("animation__1");f.removeAttribute("animation__2");c.removeAttribute("animation__1");c.removeAttribute("animation__2");c.removeAttribute("animation__Ign");c.removeAttribute("animation__3");c.removeAttribute("animation__4");c.removeAttribute("animation__L");c.setAttribute("animation__1","dur: 1000; property: position ; from: "+g.x+" "+g.y+" "+g.z+"; to: "+e.x+" "+b+" "+e.z);f.setAttribute("animation__1","delay: 1000; dur: 250; property: position ; from: 0 0 0; to: 0 -0.007 0");
c.setAttribute("animation__2","delay: 2000; dur: 1000; property: rotation; from: 0 0 0; to: 0 0 150");c.setAttribute("animation__Ign","delay: 3000; dur: 500; property: position ; from: "+e.x+" "+b+" "+e.z+"; to: "+e.x+" "+d+" "+e.z);c.setAttribute("animation__3","delay: 5500; dur: 500; property: position ; from: "+e.x+" "+d+" "+e.z+"; to: "+e.x+" "+b+" "+e.z);c.setAttribute("animation__4","delay: 6000; dur: 1000; property: rotation; from: 0 0 150; to: 0 0 0");f.setAttribute("animation__2","delay: 7000; dur: 250; property: position ; from: 0 -0.007 0; to: 0 0 0");
c.setAttribute("animation__L","delay: 7500; dur: 1000; property: position ; from: "+e.x+" "+b+" "+e.z+"; to: "+g.x+" "+g.y+" "+g.z)}else Speak(Msg.SsCantUseLighter)}
function ScNichromeClick(a){if(!AnimRunning){if(!a){for(var b=$jscomp.makeIterator(TestTube),d=b.next();!d.done;d=b.next())if(d=d.value,!d.AnaID&&1===d.ReaNum&&d.ReaID[0]==REA_ID_HCL_CONC){a=d;break}if(!a){NicromeError(Msg.SsFlameTestHCl);return}}switch(a.Type){case GLASS_TYPE_BUNSEN:if(!Bunsen.Burning){NicromeError(Msg.SsFlameTestBunsen);return}if(!Bunsen.Ox){NicromeError(Msg.SsFlameTestOx);return}break;case GLASS_TYPE_TESTTUBE:if(a.AnaID||1!==a.ReaNum||a.ReaID[0]!==REA_ID_HCL_CONC){NicromeError(Msg.SsFlameTestWrongTube);
return}break;case GLASS_TYPE_WATCHGLASS:if(1<WatchGlass.ReaNum||WatchGlass.AnaID&&WatchGlass.ReaNum||!WatchGlass.AnaID&&!WatchGlass.ReaNum){NicromeError(Msg.SsFlameTestAna);return}break;default:return}if(Nichrome.CleanCount&&a.Type!==GLASS_TYPE_TESTTUBE&&!Nichrome.ReaNum)NicromeError(Msg.SsFlameTestNiCr);else{d=Nichrome.Handle;var c=d.getAttribute("position");d.removeAttribute("animation__1");d.removeAttribute("animation__2");d.removeAttribute("animation__3");d.removeAttribute("animation__5");d.removeAttribute("animation__6");
d.removeAttribute("animation__L");AnimRunning=!0;b=PositionToLocal(Workbench,a.Handle);switch(a.Type){case GLASS_TYPE_BUNSEN:var f=6E3;var g=b.y+.3;var e=c.z+.05;var h=60;b.x+=.1;b.y+=.21;a=d.querySelector("#WireTip");d.removeAttribute("animation__FlameTestB");d.removeAttribute("animation__FlameTestE");a.removeAttribute("animation__1");a.removeAttribute("animation__2");a.removeAttribute("animation__3");a.removeAttribute("animation__4");d.setAttribute("animation__FlameTestB","delay: 1000; dur: 500; property: position ; from: "+
b.x+" "+g+" "+b.z+"; to: "+b.x+" "+b.y+" "+b.z);a.setAttribute("animation__1","delay: 1500; dur: 500; property: components.material.material.color; type: color; from: #808080; to: #FF0000");a.setAttribute("animation__2","delay: 1500; dur: 500; property: components.material.material.emissive; type: color; from: #000; to: #FF0000");a.setAttribute("animation__3","delay: 5500; dur: 500; property: components.material.material.color; type: color; from: #FF0000; to: #808080");a.setAttribute("animation__4",
"delay: 5500; dur: 500; property: components.material.material.emissive; type: color; from: #FF0000; to: #000");d.setAttribute("animation__FlameTestE","delay: 5500; dur: 500; property: position ; from: "+b.x+" "+b.y+" "+b.z+"; to: "+b.x+" "+g+" "+b.z);break;case GLASS_TYPE_TESTTUBE:f=2500;g=b.y+.17;e=c.z;h=0;b.y-=.06;Nichrome.ReaID[0]=REA_ID_HCL_CONC;Nichrome.ReaNum=1;break;case GLASS_TYPE_WATCHGLASS:f=2500,g=b.y,e=c.z,h=60,b.x+=.1,b.y-=.035,Nichrome.CleanCount||(Nichrome.AnaID=WatchGlass.AnaID?WatchGlass.AnaID:
ReaId2AnaId(WatchGlass.ReaID[0])),Nichrome.CleanCount=NICHROME_CLEAN_MIN}2500===f&&(d.removeAttribute("animation__D"),d.removeAttribute("animation__U"),d.setAttribute("animation__D","delay: 1000; dur: 500; property: position ; from: "+b.x+" "+g+" "+b.z+"; to: "+b.x+" "+b.y+" "+b.z),d.setAttribute("animation__U","delay: 2000; dur: 500; property: position ; from: "+b.x+" "+b.y+" "+b.z+"; to: "+b.x+" "+g+" "+b.z));d.setAttribute("animation__1","dur: 500; property: position ; from: "+c.x+" "+c.y+" "+
c.z+"; to: "+c.x+" "+g+" "+e);d.setAttribute("animation__2","dur: 500; property: rotation; from: -90 0 0; to: -180 0 "+h);d.setAttribute("animation__3","delay: 500; dur: 500; easing: linear;  property: position ; from: "+c.x+" "+g+" "+e+"; to: "+b.x+" "+g+" "+b.z);d.setAttribute("animation__5","delay: "+f+"; dur: 500; property: position ; from: "+b.x+" "+g+" "+b.z+"; to: "+c.x+" "+g+" "+e);f+=500;d.setAttribute("animation__6","delay: "+f+"; dur: 500; property: rotation; from: -180 0 "+h+"; to: -90 0 0");
d.setAttribute("animation__L","delay: "+f+"; dur: 500; property: position ; from: "+c.x+" "+g+" "+e+"; to: "+c.x+" "+c.y+" "+c.z)}}}
function ScReagentClick(a){var b,d,c,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){if(1==g.nextAddress){if(AnimRunning)return g.return();"string"==typeof a&&(a=Scene.querySelector("#"+a));if(a==AnalyteHandle&&!AnalyteID)return ShowError(Msg.SsBeforeAna,ScMenuAna),g.return();b=0;if(!GlassReady.Obj||GlassReady.Obj.Type!==GLASS_TYPE_STIRRER&&GlassReady.Obj.Type!==GLASS_TYPE_DROPPER)return g.jumpTo(2);ScGlassWareClick(GlassReady.Obj,GLASS_CLICK_LEAVE);return g.yield(WaitAnimEnd(500),
2)}AnimRunning=!0;if(ReaReady.Handle&&(d=document.querySelector("#AnimReaRevTrack"),d.querySelector("#Pt2").setAttribute("position",ReaReady.x+" "+ReaReady.y+" "+(ReaReady.z+REA_ANIM_SOLID_OFFSET)),d.querySelector("#Pt3").setAttribute("position",ReaReady.x+" "+ReaReady.y+" "+ReaReady.z),ReaReady.State==PHYS_STATE_SOLID&&(d=document.querySelector("#AnimReaCapRevTrack"),d.querySelector("#Pt2").setAttribute("position",ReaReady.CapX+" "+(ReaReady.CapY+REA_ANIM_LIQUID_OFFSET)+" "+ReaReady.CapZ),d.querySelector("#Pt3").setAttribute("position",
ReaReady.CapX+" "+ReaReady.CapY+" "+ReaReady.CapZ),ReaReady.Handle.querySelector("#Cap").setAttribute("alongpath","delay: 0; curve: #AnimReaCapRevTrack"),b=1E3),ReaReady.Handle.setAttribute("alongpath","delay: "+b+"; curve: #AnimReaRevTrack"),ReaReady.Handle===a))return ReaReady.Handle=null,ReaReady.Pipette=null,setTimeout(function(){AnimRunning=!1},b+1E3),g.return();c=a.getAttribute("position");ReaReady.Adspect=parseInt(a.getAttribute("ReaPhysicalAdspect"));ReaReady.Id=parseInt(a.id.split("_")[1]);
ReaReady.Handle=a;ReaReady.x=c.x;ReaReady.y=c.y;ReaReady.z=c.z;ReaReady.Water=eval(a.getAttribute("ReaWater"));ReaReady.WaterMisc=eval(a.getAttribute("ReaWaterMisc"));d=document.querySelector("#AnimReaTrack");d.querySelector("#Pt1").setAttribute("position",ReaReady.x+" "+ReaReady.y+" "+ReaReady.z);d.querySelector("#Pt2").setAttribute("position",ReaReady.x+" "+ReaReady.y+" "+(ReaReady.z+REA_ANIM_SOLID_OFFSET));a.setAttribute("alongpath","delay: "+b+"; curve: #AnimReaTrack");"solid"==a.getAttribute("ReaPhysicalState")?
(f=a.querySelector("#Cap"),c=f.getAttribute("position"),ReaReady.CapX=c.x,ReaReady.CapY=c.y,ReaReady.CapZ=c.z,ReaReady.Color=a.querySelector("#Solid").getAttribute("color"),d=document.querySelector("#AnimReaCapTrack"),d.querySelector("#Pt1").setAttribute("position",c.x+" "+c.y+" "+c.z),d.querySelector("#Pt2").setAttribute("position",c.x+" "+(c.y+REA_ANIM_LIQUID_OFFSET)+" "+c.z),f.setAttribute("alongpath","delay: "+(b+1E3)+"; curve: #AnimReaCapTrack"),ReaReady.State=PHYS_STATE_SOLID,ReaReady.Pipette=
null,b+=1E3):(ReaReady.Color=a.querySelector("#Liquid").getAttribute("color"),ReaReady.Pipette=a.querySelector("#Pipette"),ReaReady.State=PHYS_STATE_LIQUID);setTimeout(function(){AnimRunning=!1},b+1E3);g.jumpToEnd()})}
function ScReaPipetteClick(a){if(!AnimRunning)if(!ReaReady.Pipette||!GlassReady.Handle||a&&a!==ReaReady.Pipette.querySelector("#Rubber"))Speak(Msg.SsCantUseDropper);else{var b=GlassReady.Obj;if(!b.Reagent)Speak(Msg.SsCantAddReagent);else if(GlassIsClean(b)){if(GlassReady.Obj.Type===GLASS_TYPE_TESTTUBE){if(b.PaperID===REA_ID_UNIVIND){Speak(Msg.SsCantAddReagentInd);return}if(ReaReady.Id===REA_ID_CH2CL2&&-1!==b.ReaID.indexOf(REA_ID_CH2CL2)){Speak(Msg.SsCantAddCH2Cl22);return}}else if(ReaReady.Id===REA_ID_CH2CL2){Speak(Msg.SsCantAddCH2Cl21);
return}RingTest=RingTestCheck(b)&&b.Stirred&&ReaReady.Id===REA_ID_H2SO4_CONC;if(b.Type===GLASS_TYPE_TESTTUBE&&b.PaperID===REA_ID_PAPER){if(b.PaperReaID){Speak(b.PaperReaID===ReaReady.Id?Msg.SsCantAddReagentPaper2:Msg.SsCantAddReagentPaper1);return}b.PaperColor=ReaReady.Color;b.PaperReaID=ReaReady.Id;b.PaperWater=!0}else ReaReady.Water&&(b.Water=!0),b.LiqLvl<b.LiqLvlMax&&++b.LiqLvl,ReaReady.Id===REA_ID_CH2CL2&&(b.OrgColor=ReaReady.Color?ReaReady.Color:COLOR_WHITE),b.ReaNum?(b.LiqColor=ColorBlend(b.LiqColor,
ReaReady.Color,1/b.LiqLvl),ReaAdd(b,ReaReady.Id,1,ADSPECT_LIQUID)&&(b.Stirred=1===b.ReaNum&&!AnaID)):(ReaAdd(b,ReaReady.Id,1,ADSPECT_LIQUID),b.LiqColor=ReaReady.Color?ReaReady.Color:COLOR_WHITE,b.Stirred=!1),b.CentTime=0,b.Clean=!1,b.Stirred=!1;b.HeatTime=0;var d=GlassReady.Handle,c=500,f=ReaReady.Pipette,g=f.getAttribute("position"),e=PositionToLocal(ReaReady.Handle,d),h=e.y+.1,k=e.y;a=ReaReady.Pipette.querySelector("#Rubber");switch(b.Type){case GLASS_TYPE_BEAKER:h=e.y+.5;break;case GLASS_TYPE_CURCIBLE:k=
e.y-.2;break;case GLASS_TYPE_TESTTUBE:h=e.y+.3;k=RingTest?e.y:e.y+(b.PaperID?.2:-.1);break;case GLASS_TYPE_WATCHGLASS:k=e.y-.6}if(RingTest){c=3E3;var l=d.getAttribute("rotation"),m=l.z-45;d.removeAttribute("animation__1");d.removeAttribute("animation__2");d.setAttribute("animation__1","dur: 1000; property: rotation; from: "+l.x+" "+l.y+" "+l.z+"; to: "+l.x+" "+l.y+" "+m);d.setAttribute("animation__2","delay: "+(3700+c)+"; dur: 1500; property: rotation; from: "+l.x+" "+l.y+" "+m+"; to: "+l.x+" "+l.y+
" "+l.z);l=d.getAttribute("rotation");m=l.z-45;f.removeAttribute("animation__4r");f.removeAttribute("animation__9r");f.setAttribute("animation__4r","delay: 1600; dur: 500; property: rotation; from: "+l.x+" "+l.y+" "+l.z+"; to: "+l.x+" "+l.y+" "+m);f.setAttribute("animation__9r","delay: "+(3700+c)+"; dur: 1000; property: rotation; from: "+l.x+" "+l.y+" "+m+"; to: "+l.x+" "+l.y+" "+l.z)}a.removeAttribute("animation__1");a.removeAttribute("animation__2");f.removeAttribute("animation__3");f.removeAttribute("animation__4");
f.removeAttribute("animation__5");a.removeAttribute("animation__6");a.removeAttribute("animation__7");f.removeAttribute("animation__8");f.removeAttribute("animation__9");f.removeAttribute("animation__L");AnimRunning=!0;a.setAttribute("animation__1","dur: 500; property: scale; from: 1 1 1; to: 0.5 1 1");a.setAttribute("animation__2","delay: 600; dur: 500; property: scale; from: 0.5 1 1; to: 1 1 1");f.setAttribute("animation__3","delay: 1100; dur: 500; property: position ; from: "+g.x+" "+g.y+" "+g.z+
"; to: "+g.x+" "+h+" "+g.z);f.setAttribute("animation__4","delay: 1600; dur: 500; property: position ; from: "+g.x+" "+h+" "+g.z+"; to: "+e.x+" "+h+" "+e.z);f.setAttribute("animation__5","delay: 2100; dur: 500; property: position; ; from: "+e.x+" "+h+" "+e.z+"; to: "+e.x+" "+k+" "+e.z);a.setAttribute("animation__6","delay: 2600; dur: "+c+"; property: scale; from: 1 1 1; to: 0.5 1 1");setTimeout(function(){for(var n=b.Handle.querySelectorAll('[id^="Liquid"]'),q=0;q<n.length;q++)n[q].setAttribute("visible",
!1);if(n=b.Handle.querySelector("#Liquid-"+10*b.LiqLvl))ColorSet(n,b.LiqColor),n.setAttribute("visible",!0);Reaction(b)},2600+c);a.setAttribute("animation__7","delay: "+(2700+c)+"; dur: 500; property: scale; from: 0.5 1 1; to: 1 1 1");f.setAttribute("animation__8","delay: "+(3200+c)+"; dur: 500; property: position ; from: "+e.x+" "+k+" "+e.z+"; to: "+e.x+" "+h+" "+e.z);f.setAttribute("animation__9","delay: "+(3700+c)+"; dur: 500; property: position ; from: "+e.x+" "+h+" "+e.z+"; to: "+g.x+" "+h+" "+
g.z);f.setAttribute("animation__L","delay: "+(4200+c)+"; dur: 500; property: position ; from: "+g.x+" "+h+" "+g.z+"; to: "+g.x+" "+g.y+" "+g.z)}}}
function ScSmellClick(a){a||(a=GlassReady.Obj);if(a===TestTube){a=TestTube1;for(var b=$jscomp.makeIterator(TestTube),d=b.next();!d.done;d=b.next())if(d=d.value,d===GlassReady.Obj){a=d;break}}if(a){if(a.Dock===Centrifuge.Handle&&!Centrifuge.Open){Speak(Msg.SsSmellTubeCent);return}if(a.Type===GLASS_TYPE_TESTTUBE&&a.PaperID){Speak(Msg.SsSmellTubePaper);return}}PlaySound(Scene.querySelector("#SND_Sniff"));setTimeout(function(){a?a.SmellID===SMELL_NONE?ShowError(Msg.SsSmellNone):ShowError(Msg.SsSmell+
" "+GetSmellByID(a.SmellID)):Bunsen.On&&!Bunsen.Burning?Speak(Msg.SsSmellGas1):Speak(Msg.SsSmellNoneAmbient)},1500)}
function ScSpatulaClick(){if(!AnimRunning){var a=GlassReady.Obj;if(ReaReady.Handle&&ReaReady.State==PHYS_STATE_SOLID&&a&&a.Reagent){if(a.PaperID){if(ReaReady.Id===REA_ID_PAPER||ReaReady.Id===REA_ID_UNIVIND){Speak(Msg.SsPaperAlready);return}if(ReaReady.State===PHYS_STATE_SOLID){Speak(a.Type===GLASS_TYPE_TESTTUBE?Msg.SsPaperTubeClose:Msg.SsPaperWithSolid);return}}if(a.ReaNum&&-1!==a.ReaID.indexOf(REA_ID_CU))Speak(Msg.SsCuAlready);else if(GlassIsClean(a)){var b=ReaReady.Handle.getAttribute("position"),
d=Spatula.getAttribute("position"),c=PositionToLocal(Workbench,GlassReady.Handle);if(ReaReady.Id===REA_ID_PAPER||ReaReady.Id===REA_ID_UNIVIND)a.PaperID=ReaReady.Id,a.PaperColor=ReaReady.Color;else if(ReaReady.Handle==AnalyteHandle){if(a.AnaID){Speak(Msg.SsAnaAlready);return}a.AnaID=AnalyteID;a.AnaQty+=1;a.Stirred=!a.ReaNum&&!a.Water}else ReaAdd(a,ReaReady.Id,1,ReaReady.Adspect),a.Stirred=a.ReaNum?!1:!a.Water;a.CentTime=0;a.HeatTime=0;a.SolidColor=a.SolidColor?ColorBlend(a.SolidColor,ReaReady.Color):
ReaReady.Color;switch(GlassReady.Obj.Type){case GLASS_TYPE_BEAKER:c.y+=.15;break;case GLASS_TYPE_CURCIBLE:c.y+=.07;break;case GLASS_TYPE_TESTTUBE:c.y+=.12}Spatula.removeAttribute("animation__1");Spatula.removeAttribute("animation__2");Spatula.removeAttribute("animation__3");Spatula.removeAttribute("animation__4");Spatula.removeAttribute("animation__5");Spatula.removeAttribute("animation__6");Spatula.removeAttribute("animation__7");Spatula.removeAttribute("animation__8");Spatula.removeAttribute("animation__9");
Spatula.removeAttribute("animation__10");Spatula.removeAttribute("animation__L");AnimRunning=!0;Spatula.setAttribute("animation__1","dur: 500; property: rotation; from: 90 0 0; to: 45 90 0");Spatula.setAttribute("animation__2","dur: 500; property: position ; from: "+d.x+" "+d.y+" "+d.z+"; to: "+d.x+" "+(d.y+.1)+" "+d.z);Spatula.setAttribute("animation__3","delay: 500; dur: 500; property: position ; from: "+d.x+" "+(d.y+.1)+" "+d.z+"; to: "+(b.x+.07)+" "+(d.y+.1)+" "+b.z);Spatula.setAttribute("animation__4",
"delay: 1000; dur: 500; property: position ; from: "+(b.x+.07)+" "+(d.y+.1)+" "+b.z+"; to: "+(b.x+.06)+" "+(d.y+.075)+" "+b.z);Spatula.setAttribute("animation__5","delay: 1500; dur: 250; property: rotation; from: 45 90 0; to: 70 90 0");Spatula.setAttribute("animation__6","delay: 1750; dur: 500; property: position ; from: "+(b.x+.06)+" "+(d.y+.075)+" "+b.z+"; to: "+(c.x+.07)+" "+c.y+" "+c.z);Spatula.setAttribute("animation__7","delay: 2250; dur: 250; property: rotation; from: 70 90 0; to: 0  90 0");
Spatula.setAttribute("animation__8","delay: 2250; dur: 250; property: position ; from: "+(c.x+.07)+" "+c.y+" "+c.z+"; to: "+c.x+" "+c.y+" "+c.z);Spatula.setAttribute("animation__9","delay: 2700; dur: 250; property: rotation; from: 0 90 0; to: 45 90 0");Spatula.setAttribute("animation__L","delay: 2850; dur: 500; property: position ; from: "+c.x+" "+c.y+" "+c.z+"; to: "+d.x+" "+d.y+" "+d.z);Spatula.setAttribute("animation__10","delay: 3000; dur: 250; property: rotation; from: 45 90 0; to: 90 0 0")}}else Speak(Msg.SsCantUseSpatula)}}
function ScStirrerClick(a){var b,d,c,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){if(1==g.nextAddress){if(AnimRunning)return g.return();if(!a.Stirrer)return Speak(Msg.SsCantUseStirrer),g.return();if(GlassIsEmpty(a))return Speak(Msg.SsStirrerNothing),g.return();if(a.Burning)return Speak(Msg.SsCantBurning),g.return();if(a.Type===GLASS_TYPE_TESTTUBE&&a.PaperID)return Speak(Msg.SsStirrerPaper),g.return();if(!GlassSameSubst(Stirrer,a)&&!GlassIsClean(Stirrer))return g.return();c=Stirrer.Handle.querySelector("#RotCent");
Stirrer.AnaID=a.AnaID;Stirrer.Clean=!1;Stirrer.ReaAdspect=Array.from(a.ReaAdspect);Stirrer.ReaID=Array.from(a.ReaID);Stirrer.ReaNum=a.ReaNum;Stirrer.SmellID=a.SmellID;Stirrer.Water=a.Water;switch(a.Type){case GLASS_TYPE_BEAKER:d=0;b=.057;break;case GLASS_TYPE_CURCIBLE:d=0;b=.05;break;case GLASS_TYPE_TESTTUBE:d=.18;b=.035;break;case GLASS_TYPE_WATCHGLASS:d=0,b=.05}AnimRunning=!0;return g.yield(Sleep(MoveToTarget(a.Handle,d,b)),2)}if(3!=g.nextAddress)return c.removeAttribute("animation__1"),Stirrer.Handle.removeAttribute("animation__1"),
Stirrer.Handle.removeAttribute("animation__2"),f=Stirrer.Handle.getAttribute("position"),Stirrer.Handle.setAttribute("animation__1","dur: 100; property: position ; from: "+f.x+" "+f.y+" "+f.z+"; to: "+(f.x+.007)+" "+f.y+" "+f.z),c.setAttribute("animation__1","dur: 500; property: rotation; from: 0 0 0; to: 0 360 0; easing: linear; loop: 6"),Stirrer.Handle.setAttribute("animation__2","delay: 3000; dur: 100; property: position ; from: "+(f.x+.007)+" "+f.y+" "+f.z+"; to: "+f.x+" "+f.y+" "+f.z),g.yield(Sleep(ReturnFromTarget(3100,
!0)),3);a.Stirred=!0;Reaction(a);a.Water&&GlassPrecipitate(a)&&a.LiqAdspect!==ADSPECT_LIQUID_SUSP&&(a.LiqAdspect=ADSPECT_LIQUID_SUSP,LiquidUpdate(a));g.jumpToEnd()})}
function ScTrashClick(){if(!AnimRunning)if(GlassReady.Handle)if(GlassReady.Obj.Type===GLASS_TYPE_LIGHTER)Speak(Msg.SsCantEmptyLighter);else if(GlassReady.Obj.Type===GLASS_TYPE_STIRRER)Speak(Msg.SsCantEmptyStirrer);else if(GlassIsEmpty(GlassReady.Obj))Speak(Msg.SsAlreadyEmpty);else{var a=PositionToLocal(GlassReady.Obj.Type===GLASS_TYPE_TESTTUBE?Rack:Workbench,Trash),b=GlassReady.Handle,d=b.getAttribute("position"),c=b.getAttribute("rotation"),f=0,g=c.z;a.y=d.y;switch(GlassReady.Obj.Type){case GLASS_TYPE_BEAKER:var e=
2E3;a.x+=.05;a.y+=.04;g+=120;break;case GLASS_TYPE_CURCIBLE:e=1E3;a.x+=.02;g+=70;break;case GLASS_TYPE_DROPPER:e=1E3;a.y+=.1;break;case GLASS_TYPE_TESTTUBE:e=1E3;a.x-=.1;a.y=d.y-1.5;g-=170;f=c.z-45;break;case GLASS_TYPE_WATCHGLASS:e=500,a.x-=.02,g+=45}b.removeAttribute("animation__1");b.removeAttribute("animation__2");b.removeAttribute("animation__3");b.removeAttribute("animation__L");AnimRunning=!0;f&&(b.removeAttribute("animation__0"),b.removeAttribute("animation__4"),b.setAttribute("animation__0",
"dur: 1000; property: rotation; from: "+c.x+" "+c.y+" "+c.z+"; to: "+c.x+" "+c.y+" "+f),b.setAttribute("animation__4","delay: "+(2E3+e)+"; dur: 1000; property: rotation; from: "+c.x+" "+c.y+" "+f+"; to: "+c.x+" "+c.y+" "+c.z));b.setAttribute("animation__1","dur: 1000; property: position; from: "+d.x+" "+d.y+" "+d.z+"; to: "+a.x+" "+a.y+" "+a.z);b.setAttribute("animation__2","delay: 1000; dur: 500; property: rotation; from: "+c.x+" "+c.y+" "+f+"; to: "+c.x+" "+c.y+" "+g);if(GlassReady.Obj.Type===GLASS_TYPE_DROPPER){var h=
b.querySelector("#Rubber");h.removeAttribute("animation__1t");h.removeAttribute("animation__2t");h.setAttribute("animation__1t","delay: 1500; dur: 500; property: scale; from: 1 1 1; to: 0.5 1 1");h.setAttribute("animation__2t","delay: 2100; dur: 500; property: scale; from: 0.5 1 1; to: 1 1 1")}b.setAttribute("animation__3","delay: "+(1500+e)+"; dur: 500; property: rotation; from: "+c.x+" "+c.y+" "+g+"; to: "+c.x+" "+c.y+" "+f);b.setAttribute("animation__L","delay: "+(2E3+e)+"; dur: 1000; property: position; from: "+
a.x+" "+a.y+" "+a.z+"; to: "+d.x+" "+d.y+" "+d.z);setTimeout(function(){(GlassReady.Obj.Water||-1!==GlassReady.Obj.ReaID.indexOf(REA_ID_CH2CL2))&&PlaySound(Trash.querySelector("#SND_LiquidDrain"));GlassReady.Obj.Type!==GLASS_TYPE_DROPPER||GlassWater(GlassReady.Obj)?GlassEmpty(GlassReady.Obj):GlassEmpty(GlassReady.Obj,~EMPTY_SUBST)},1500+e/2)}else Speak(Msg.SsCantEmpty)}
function ScTrashDblClick(){var a,b,d,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:if(AnimRunning)return f.return();if(GlassIsEmpty(Beaker)&&GlassIsEmpty(Curcible)&&GlassIsEmpty(Dropper)&&GlassIsEmpty(TestTube1)&&GlassIsEmpty(TestTube2)&&GlassIsEmpty(TestTube3)&&GlassIsEmpty(TestTube4)&&GlassIsEmpty(WatchGlass))return Speak(Msg.SsAlreadyEmptyAll),f.return();a=GlassReady.Obj;if(!a||!(a===Dropper&&GlassIsEmpty(Dropper)||a!==Beaker&&a!==Curcible&&a!==Dropper&&
a!==WatchGlass&&a!==TestTube1&&a!==TestTube2&&a!==TestTube3&&a!==TestTube4)){f.jumpTo(2);break}ScGlassWareClick(a,GLASS_CLICK_LEAVE);return f.yield(WaitAnimEnd(500),3);case 3:a=null;case 2:if(!a||GlassIsEmpty(a)){f.jumpTo(4);break}ScTrashClick();return f.yield(WaitAnimEnd(500),5);case 5:if(a!==Dropper){f.jumpTo(4);break}ScGlassWareClick(Dropper,GLASS_CLICK_LEAVE);return f.yield(WaitAnimEnd(500),4);case 4:if(a===Beaker){f.jumpTo(8);break}return f.yield(ScTrashObj(Beaker),8);case 8:if(a===Curcible){f.jumpTo(10);
break}return f.yield(ScTrashObj(Curcible),10);case 10:if(a===Dropper||GlassIsEmpty(Dropper)){f.jumpTo(12);break}return f.yield(ScTrashObj(Dropper),13);case 13:return ScGlassWareClick(Dropper,GLASS_CLICK_LEAVE),f.yield(WaitAnimEnd(500),12);case 12:if(a===WatchGlass){f.jumpTo(15);break}return f.yield(ScTrashObj(WatchGlass),15);case 15:b=$jscomp.makeIterator(TestTube),d=b.next();case 17:if(d.done){f.jumpTo(0);break}c=d.value;if(a===c||c.Dock===Centrifuge.Handle&&!Centrifuge.Open){f.jumpTo(18);break}return f.yield(ScTrashObj(c),
18);case 18:d=b.next(),f.jumpTo(17)}})}function ScTrashObj(a){return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress){if(GlassIsEmpty(a))return b.return();ScGlassWareClick(a,GLASS_CLICK_TAKE);return b.yield(WaitAnimEnd(500),2)}if(3!=b.nextAddress)return ScTrashClick(),b.yield(WaitAnimEnd(500),3);ScGlassWareClick(a,GLASS_CLICK_LEAVE);return b.yield(WaitAnimEnd(500),0)})}
function ScTubePaperClick(a){if(!AnimRunning){if(!a&&(a=GlassReady.Obj,!a)){Speak(Msg.SsCantEmpty);return}if(a.PaperID)if(a.Type!==GLASS_TYPE_TESTTUBE)Speak(Msg.SsPaperNoTrash);else{var b=a.Handle.querySelector("#Solid-Paper");a=PositionToLocal(a.Handle,Trash);var d=b.getAttribute("position");b.removeAttribute("animation__1");b.removeAttribute("animation__L");AnimRunning=!0;b.setAttribute("animation__1","dur: 1000; property: position; from: "+d.x+" "+d.y+" "+d.z+"; to: "+a.x+" "+d.y+" "+a.z);b.setAttribute("animation__L",
"delay: 1000; dur: 1000; property: position; from: "+a.x+" "+d.y+" "+a.z+"; to: "+a.x+" "+a.y+" "+a.z)}else Speak(Msg.SsPaperNotPresent)}}
function ScWashBottleClick(){var a,b,d,c,f,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress){if(AnimRunning)return e.return();a=GlassReady.Obj;if(!a||!a.WashBottle)return Speak(Msg.SsCantUseWashBottle),e.return();b=WashBottle.Handle;if(a!==Stirrer)return e.jumpTo(2);GlassEmpty(Stirrer);return e.yield(Sleep(MoveToTarget(Trash,.1)),3)}2!=e.nextAddress&&(a.Water=!0);d=b.querySelector("#Bottle");c=PositionToLocal(Workbench,GlassReady.Handle);f=c.y+.05;a.HeatTime=0;
RingTest=!1;c.x+=.19;switch(GlassReady.Obj.Type){case GLASS_TYPE_BEAKER:g=c.y-.03;break;case GLASS_TYPE_CURCIBLE:case GLASS_TYPE_STIRRER:g=c.y-.07;break;case GLASS_TYPE_TESTTUBE:g=c.y+(GlassReady.Obj.PaperID?-.02:-.07);break;case GLASS_TYPE_WATCHGLASS:g=c.y-.14}b.removeAttribute("animation__1");b.removeAttribute("animation__2");b.removeAttribute("animation__3");b.removeAttribute("animation__4");d.removeAttribute("animation__5");d.removeAttribute("animation__6");b.removeAttribute("animation__7");b.removeAttribute("animation__8");
b.removeAttribute("animation__9");b.removeAttribute("animation__L");AnimRunning=!0;b.setAttribute("animation__1","dur: 500; property: position ; from: "+WashBottle.PosX+" "+WashBottle.PosY+" "+WashBottle.PosZ+"; to: "+WashBottle.PosX+" "+f+" "+WashBottle.PosZ);b.setAttribute("animation__2","dur: 500; property: rotation; from: 0 0 0; to: 0 0 45");b.setAttribute("animation__3","delay: 500; dur: 500; property: position ; from: "+WashBottle.PosX+" "+f+" "+WashBottle.PosZ+"; to: "+c.x+" "+f+" "+c.z);b.setAttribute("animation__4",
"delay: 1000; dur: 500; property: position; ; from: "+c.x+" "+f+" "+c.z+"; to: "+c.x+" "+g+" "+c.z);d.setAttribute("animation__5","delay: 1500; dur: 500; property: scale; from: 1 1 1; to: 0.9 1 1");GlassReady.Obj===Stirrer&&ReturnFromTarget(2300,!1);d.setAttribute("animation__6","delay: 2300; dur: 500; property: scale; from: 0.9 1 1; to: 1 1 1");b.setAttribute("animation__7","delay: 2800; dur: 500; property: position ; from: "+c.x+" "+g+" "+c.z+"; to: "+c.x+" "+f+" "+c.z);b.setAttribute("animation__8",
"delay: 3300; dur: 500; property: position; ; from: "+c.x+" "+f+" "+c.z+"; to: "+WashBottle.PosX+" "+f+" "+WashBottle.PosZ);b.setAttribute("animation__9","delay: 3800; dur: 500; property: rotation; from: 0 0 45; to: 0 0 0");b.setAttribute("animation__L","delay: 3800; dur: 500; property: position ; from: "+WashBottle.PosX+" "+f+" "+WashBottle.PosZ+"; to: "+WashBottle.PosX+" "+WashBottle.PosY+" "+WashBottle.PosZ);e.jumpToEnd()})};
