var TubeSequence=[0,3,2,5,1,4];
function CentrifugeCheck(){for(var a=0,b=0;6>b;++b)Centrifuge.DockTube[b]&&++a;if(!a)return!0;if(a%2)return ShowError(Msg.SsCentOddTubes),!1;for(b=0;6>b;b+=2)if(Centrifuge.DockTube[TubeSequence[b]]&&!Centrifuge.DockTube[TubeSequence[b+1]]||!Centrifuge.DockTube[TubeSequence[b]]&&Centrifuge.DockTube[TubeSequence[b+1]])return ShowError(Msg.SsCentPosTubes),!1;for(b=0;6>b;b+=2){a=Centrifuge.DockTube[TubeSequence[b]];var c=Centrifuge.DockTube[TubeSequence[b+1]];if(a&&c&&a.LiqLvl!==c.LiqLvl)return ShowError(Msg.SsCentNotBal),
!1}return!0}function CentrifugeDoSeparation(a){a.LiqAdspect=ADSPECT_LIQUID_NONE;a.CentTime=0;LiquidUpdate(a);var b=a.Handle.querySelector("#Solid");b.setAttribute("visible",!0);ColorSet(b,a.SolidColor)}
function CentrifugeOpen(a){if(a&&Centrifuge.Open)ShowError(Msg.SsCentAlrOpen);else if(a||Centrifuge.Open){if(a){if(!Centrifuge.On){ShowError(Msg.SsCentOpenOff);return}if(Centrifuge.Run||Centrifuge.Time){ShowError(Msg.SsCentOpenRun);return}if(Centrifuge.Lock){ShowError(Msg.SsCentOpenLock);return}if(!Centrifuge.Time){for(var b=0;6>b;++b)if(Centrifuge.DockTube[b]){var c=Centrifuge.DockTube[b].Handle.getAttribute("position"),d=PositionToLocal(Rack,Centrifuge.hTube[b]);Centrifuge.DockTube[b].Handle.setAttribute("position",
d.x+" "+c.y+" "+d.z)}CentrifugeSeparate();Centrifuge.hCover.removeAttribute("animation__Open");Centrifuge.hCover.setAttribute("animation__Open","dur: 500; property: rotation; to: -90 0 0");Centrifuge.Open=!0;PlaySound(Centrifuge.hCover.querySelector("#SND_OpenCover"))}}else{if(!CentrifugeCheck())return;Centrifuge.hCover.removeAttribute("animation__Close");Centrifuge.hCover.setAttribute("animation__Close","dur: 500; property: rotation; to: 0 0 0");Centrifuge.Lock=!0;PlaySound(Centrifuge.hCover.querySelector("#SND_OpenCover"))}Centrifuge.Open=
a}else ShowError(Msg.SsCentAlrClose)}
function CentrifugePower(a){a&&Centrifuge.On?ShowError(Msg.SsCentAlrOn):a||Centrifuge.On?(Centrifuge.hLedPower.setAttribute("color",a?"#3eea3e":"#005700"),Centrifuge.hLedPower.setAttribute("event-set__leave","_event: mouseleave; material.color: "+(a?"#3eea3e":"#005700")),PlaySound(Centrifuge.hLedPower.querySelector(a?"#SND_ButtonOn":"#SND_ButtonOff")),a||Centrifuge.Handle.querySelector("#SND_CentRun").components.sound.stopSound(),Centrifuge.On=a,CentrifugeTime(Centrifuge.Time,!0)):ShowError(Msg.SsCentAlrOff)}
function CentrifugePutTube(a){if(!AnimRunning)if(Centrifuge.Open){var b;if(a)for(b=0;6>b&&Centrifuge.hTube[b]!=a;++b);else{b=6;for(a=0;6>a;a+=2){if(Centrifuge.DockTube[TubeSequence[a]]&&!Centrifuge.DockTube[TubeSequence[a+1]]){b=TubeSequence[a+1];break}if(!Centrifuge.DockTube[TubeSequence[a]]&&Centrifuge.DockTube[TubeSequence[a+1]]){b=TubeSequence[a];break}}if(6===b){for(b=0;6>b&&Centrifuge.DockTube[TubeSequence[b]];++b);b=TubeSequence[b]}a=Centrifuge.hTube[b]}if(GlassReady.Obj)if(GlassReady.Obj.Centrifuge)if(GlassReady.Obj.PaperID)ShowError(Msg.SsCentGlassPaper);
else if(GlassIsEmpty(GlassReady.Obj))ShowError(Msg.SsCentGlassEmpty);else if(Centrifuge.DockTube[b])ShowError(Msg.SsCentSameTube);else{Centrifuge.DockTube[b]=GlassReady.Obj;b=GlassReady.Handle;var c=b.getAttribute("position");a=PositionToLocal(Rack,a);b.removeAttribute("animation__DockCent");AnimRunning=!0;b.setAttribute("animation__DockCent","dur: 500; property: position ; from: "+c.x+" "+c.y+" "+c.z+"; to: "+a.x+" "+c.y+" "+a.z)}else ShowError(Msg.SsCantPutInCent);else Centrifuge.hTube[b]||ShowError(Msg.SsSelectGlassware)}else ShowError(Msg.SsCentPutClose)}
function CentrifugeSeparate(){for(var a=0;6>a;++a){var b=Centrifuge.DockTube[a];b&&b.LiqAdspect===ADSPECT_LIQUID_SUSP&&2<=b.CentTime&&CentrifugeDoSeparation(b)}}function CentrifugeSpeed(a){2<a&&(a=0);Centrifuge.hPotSpeed.setAttribute("rotation",70+20*a+" 90 90");PlaySound(Centrifuge.hPotSpeed.querySelector("#SND_RotSwitch"));Centrifuge.Speed=a;CentrifugeUpdate()}
function CentrifugeStop(){PlaySound(Centrifuge.Handle.querySelector("#SND_CentStop"));Centrifuge.Handle.querySelector("#SND_CentStart").components.sound.stopSound();Centrifuge.Handle.querySelector("#SND_CentRun").components.sound.stopSound();clearInterval(Centrifuge.hTimer);Prefs.SoundActive||setTimeout(function(){CentrifugeStopEvent()},1E3*Asset.querySelector("#SndCentStop").duration)}
function CentrifugeStopEvent(){Centrifuge.Run=!1;CentrifugeUpdate();Centrifuge.Handle.querySelector("#Rotor").setAttribute("rotation","0 "+360*Math.random()+" 0")}
function CentrifugeTime(a,b){if(a!==Centrifuge.Time||b)4<a&&(a=0),Centrifuge.Open||(a?Centrifuge.On?Centrifuge.Run||(Centrifuge.Lock||(PlaySound(Centrifuge.hLedOpen.querySelector("#SND_Clack")),Centrifuge.Lock=!0),PlaySound(Centrifuge.Handle.querySelector("#SND_CentStart")),Centrifuge.Run=!0,Centrifuge.hTimer=setInterval(function(){CentrifugeTime(Centrifuge.Time-1,!0);for(var c=0;6>c;++c){var d=Centrifuge.DockTube[c];d&&++d.CentTime}},Centrifuge.TimeStep)):Centrifuge.Run&&CentrifugeStop():Centrifuge.On&&
Centrifuge.Time!==a&&CentrifugeStop()),Centrifuge.hPotTime.setAttribute("rotation",45*a+" -90 -90"),b||PlaySound(Centrifuge.hPotTime.querySelector("#SND_RotSwitch")),Centrifuge.Lock=!0,Centrifuge.Time=a,CentrifugeUpdate()}function CentrifugeUnlock(){Centrifuge.On?Centrifuge.Run||Centrifuge.Time?ShowError(Msg.SsCentUnlockRun):(Centrifuge.Lock&&(PlaySound(Centrifuge.hLedOpen.querySelector("#SND_Clack")),Centrifuge.Lock=!1),CentrifugeUpdate()):ShowError(Msg.SsCentUnlockOff)}
function CentrifugeUpdate(){var a=!Centrifuge.On||Centrifuge.Run||Centrifuge.Time?"#a36a00":"#d6ff0a";Centrifuge.hLedOpen.setAttribute("color",a);Centrifuge.hLedOpen.setAttribute("event-set__leave","_event: mouseleave; material.color: "+a)};
