var DEBUG=!1,DEBUG_GLASS_CLEAN=!1,ADSPECT_POWDER=1,ADSPECT_PLATE=2,ADSPECT_PAPER=3,ADSPECT_LIQUID=4,ADSPECT_SOLID=5,ADSPECT_GAS=6,ADSPECT_LIQUID_NONE=0,ADSPECT_LIQUID_SUSP=1,AFRAME_DETAIL_HI=36,AFRAME_DETAIL_LOW=18,ANA_POSITION="0.25 1.045 -0.75",BOIL_DELAY_START=3E3,BOIL_DELAY_STOP=1E3,CAMERA_MAX_X=2.9,CAMERA_MIN_X=-2.9,CAMERA_MAX_Y=1.35,CAMERA_MIN_Y=-1.7,CAMERA_RIG_OFFY=1.7,CAMERA_RIG_OFFY_VR=0,CODE_INTK=76,CODE_LENGTH=6,COLOR_COLORLESS=null,COLOR_RED="#FF0000",COLOR_WHITE="#FFFFFF",COLOR_ID_COLORLESS=
2,COLOR_ID_METALLICRED=21,COLOR_ID_WHITE=1,COOKIE_NAME="LabSim",COOKIE_EXPIRATION=30,DBLCLICK_DELAY=500,DEVICE_TYPE_DESKTOP=1,DEVICE_TYPE_MOBILE=2,DEVICE_TYPE_VR=4,EFFERV_DURATION=5E3,EMPTY_ALL=4294967295,EMPTY_LIQUID=1,EMPTY_PAPER=2,EMPTY_PLATE=4,EMPTY_SOLID=8,EMPTY_SUBST=16,EVENT_NONE=0,EVENT_BIPHASIC=7,EVENT_CLEAR_SOL=3,EVENT_CORROSION=9,EVENT_EFFERV=18,EVENT_EFFERVSLIGHT=19,EVENT_FLAME=11,EVENT_INDICATORCOL=14,EVENT_PLATECOL=20,EVENT_POWDER=21,EVENT_PRECIPITATE=6,EVENT_SUSPENSION=4,EVENT_TRIPHASIC=
8,EXPLOSION_DUR=500,EXPLOSION_SCALE=5,EXPLOSION_TIME=60,FLAME_DEF_COLOR="#020202,#0000FF,#0000FF",GETIONID_ANION=0,GETIONID_CATION1=1,GETIONID_CATION2=2,GLASS_CLICK_LEAVE=0,GLASS_CLICK_TAKE=1,GLASS_CLICK_TOGGLE=2,GLASS_CLICK_USE=3,GLASS_ID_WATCHGLASS=23,GLASS_TYPE_BEAKER=0,GLASS_TYPE_BUNSEN=1,GLASS_TYPE_CURCIBLE=2,GLASS_TYPE_DROPPER=3,GLASS_TYPE_LIGHTER=4,GLASS_TYPE_NICHROME=5,GLASS_TYPE_STIRRER=6,GLASS_TYPE_TESTTUBE=7,GLASS_TYPE_WASHBOTTLE=8,GLASS_TYPE_WATCHGLASS=9,GUI_FADETIME=500,GUI_POS_INVISIBLE=
"0 1.7 -10",GUI_POS_VISIBLE="0 1.7 -4.6",LOG_PROMPT="**** LabSim:",MATH_DEG2RAD=.01745329,MATH_RAD2DEG=57.29577951,MATH_2PI=2*Math.PI,MENUANA_BUTTON_HEIGHT=.3,MENUANA_HEIGHT=.8,MENUANA_ITEMDBYLINE=6,MENUANA_OFFSET_BEGIN_X=-7.46,MENUANA_OFFSET_BEGIN_Y=.65,MENUANA_OFFSET_X=.1,MENUANA_STEP_Y=.35,MOLID_BASO4=50,MOLID_CO2=101,MOLID_NACL=42,MOLID_NH4OH=95,MOLID_SO2=140,MOLID_FENOSO4=207,MOUSE_BUTTON_BACKWARD=3,MOUSE_BUTTON_FORWARD=4,MOUSE_BUTTON_LEFT=0,MOUSE_BUTTON_RIGHT=2,MOUSE_BUTTON_WHEEL=1,NICHROME_CLEAN_MIN=
3,PHID_5=12,PHID_NEUTRAL=3,PHID_8to10=4,PHID_ND=7,PHYS_STATE_LIQUID=0,PHYS_STATE_SOLID=1,PHYS_STATE_GAS=2,REA_ANIM_LIQUID_OFFSET=.1,REA_ANIM_SOLID_OFFSET=.2,REA_ID_BUFFER_PH5=35,REA_ID_BUFFER_PH9=34,REA_ID_CH2CL2=15,REA_ID_CH3OH=31,REA_ID_CU=32,REA_ID_DUMMYINSOL=9999,REA_ID_FESO4=23,REA_ID_HCL_6M=2,REA_ID_HCL_CONC=3,REA_ID_H2SO4=5,REA_ID_H2SO4_CONC=6,REA_ID_K2CR2O7=21,REA_ID_PAPER=42,REA_ID_UNIVIND=41,REA_QTY_CH3OH_IGN=2,REA_RINGTEST_FECONC=.66,REALIQ_LBL_OFFSET_Y=84,REASOL_LBL_OFFSET_Y=48,REA_TYPE_UNKNOWN=
0,REA_TYPE_ACIDSTRONG=1,REA_TYPE_ACIDSTRONGCO=2,REA_TYPE_ACIDWEAK=3,REA_TYPE_BASESTRONG=4,REA_TYPE_BASEWEAK=5,REA_TYPE_PRECIPITANT=6,REA_TYPE_SOLVENT=7,REA_TYPE_OXIDANT=8,REA_TYPE_REDUCING=9,REA_TYPE_INDICATOR=10,REA_TYPE_COMPLEXANT=11,REA_TYPE_BUFFER=12,REA_TYPE_DYE=13,REA_TYPE_PH=14,SCGWCLICK_NONE=0,SCGWCLICK_NOMOVEBATH=1,SCGWCLICK_TESTTUBEONLY=2,SMELL_NONE=1,SMELL_PUNGENT=10,SMELL_UNKNOWN=10,SOLGRADE_FULL=1,SOLGRADE_PARTIAL=2,SOLGRADE_INSOL=3,SUSP_OPACITY=.7,WATERBATH_MOVEUP=.05,WATERBATH_MOVEDOWN=
.095,WATERBATH_MOVEZ=-.2,TV_PROGBAR_OFFSET_X=-.25,TV_PROGBAR_WIDTH=.5,TV_MODE_LOG=0,TV_MODE_MENU=1,TV_MODE_PLAYER=2,TV_PLAYMODE_ALL=0,TV_PLAYMODE_LOOP=1,TV_PLAYMODE_SINGLE=2,TV_MAXPAGEVIDEO=14,TV_VIDEO_PATH="video/",TUBE_PAPER_POS_Y=1.15,VOICE_PITCH=1,VOICE_RATE=1,VOICE_TYPE_NONE=0,VOICE_TYPE_NATIVE=1,VOICE_TYPE_PICOSERVER=2,VOICE_TYPE_RESPONSIVE=3,AnalyteID,AnalyteHandle,annyang,Asset,Camera,CameraRig,Cursor,Device,DlgAbout,DlgAnaCode,DlgMenu,DlgMenuAna,DlgMenuSet,Floor,Gui,hDb,MbClickID,PicoTtsURI,
Rack,RingTest,Scene,Shadows,Spatula,Trash,Workbench,AnimRunning=!1,CameraRigOffsetY=CAMERA_RIG_OFFY,CleanDropperFirst=!0,CleanGlassFirst=!0,FlameTestFirst=!0,GlassTarget=null,Light=!0,NumAnalytes=0,ShownDlgName="",Voice=window.speechSynthesis,VoiceHandle=null,VoiceType=VOICE_TYPE_NATIVE,VrMode=!1,Zoom=1,GlassReady={EnterY:0,EnterS:0,Handle:null,LeaveY:0,LeaveS:0,MoveDown:0,Obj:null,StartPosX:0,StartPosY:0,StartPosZ:0},MouseTrans={x:0,y:0,CameraPosX:0,CameraPosY:0},Prefs={Changed:!1,Detail:!0,SoundActive:!0,
SpeechRecActive:!1,SpeechRecAvail:!0,VoiceActive:!0,VoiceAvail:!0},ReaReady={Id:0,Handle:null,Pipette:null,Adspect:ADSPECT_LIQUID,State:PHYS_STATE_LIQUID,Color:null,x:0,y:0,z:0,CapX:0,CapY:0,CapZ:0,Water:!0,WaterMisc:!0},Beaker={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Handle:null,Name:"Beaker",CentTime:0,Clean:!1,Dock:null,HeatTime:0,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],
ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_BEAKER,Water:!1,Bath:!1,Dropper:!0,Heater:!0,Lighter:!1,Reagent:!0,Stirrer:!0,WashBottle:!0},Bunsen={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,HeatTime:0,Name:"Bunsen",LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,
ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_BUNSEN,Water:!1,Bath:!1,Centrifuge:!1,Dropper:!1,Heater:!1,Lighter:!0,Reagent:!1,Stirrer:!1,WashBottle:!1,hTimer:null,FlameOxHandle:null,On:!1,Ox:!1,Timer:0},Centrifuge={DockTube:[null,null,null,null,null,null],Handle:null,hCover:null,hLedOpen:null,hLedPower:null,hPotSpeed:null,hPotTime:null,hTimer:null,hTube:[null,null,null,null,null,null],Lock:!0,On:!1,Open:!1,Run:!1,Speed:1,Time:0,TimeStep:6E4},
Curcible={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,HeatTime:0,Name:"Curcible",LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.5,LiqDefOpac:.5,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_CURCIBLE,Water:!1,Bath:!1,Centrifuge:!1,Dropper:!0,Heater:!0,Lighter:!0,Reagent:!0,
Stirrer:!0,WashBottle:!0},Dropper={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Handle:null,Name:"Dropper",Clean:!1,Dock:null,HeatTime:0,LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_DROPPER,Water:!1,Bath:!1,Centrifuge:!1,Dropper:!1,
Heater:!1,Lighter:!1,Stirrer:!1,Reagent:!1,WashBottle:!1},Heater={Handle:null,WhatGlass:null},Lighter={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,Handle:null,Name:"Lighter",CentTime:0,Clean:!1,Dock:null,HeatTime:0,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_LIGHTER,Water:!1,
Bath:!1,Dropper:!1,Heater:!1,Lighter:!1,Reagent:!1,Stirrer:!1,WashBottle:!1},Nichrome={AnaAdspect:ADSPECT_SOLID,AnaID:MOLID_NACL,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,CleanCount:NICHROME_CLEAN_MIN,Dock:null,Handle:null,HeatTime:0,Name:"Nichrome",LiqAdspect:ADSPECT_LIQUID_NONE,LiqLvl:0,LiqLvlMax:0,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,
Type:GLASS_TYPE_NICHROME,Water:!1,Bath:!1,Centrifuge:!1,Dropper:!1,Heater:!1,Lighter:!1,Stirrer:!1,Reagent:!1,WashBottle:!1},Stirrer={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,HeatTime:0,Name:"Stirrer",LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,
SolidColor:null,Stirred:!0,Type:GLASS_TYPE_STIRRER,Water:!1,Bath:!1,Centrifuge:!1,Dropper:!1,Heater:!1,Lighter:!1,Stirrer:!1,Reagent:!1,WashBottle:!0},TestTube1={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,HeatTime:0,Name:"TestTube1",LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,
ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_TESTTUBE,Water:!1,Bath:!0,Centrifuge:!0,Dropper:!0,Heater:!1,Lighter:!1,Stirrer:!0,Reagent:!0,WashBottle:!0},TestTube2={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,HeatTime:0,Name:"TestTube2",LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,
ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_TESTTUBE,Water:!1,Bath:!0,Centrifuge:!0,Dropper:!0,Heater:!1,Lighter:!1,Stirrer:!0,Reagent:!0,WashBottle:!0},TestTube3={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,HeatTime:0,Name:"TestTube3",LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,
PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_TESTTUBE,Water:!1,Bath:!0,Centrifuge:!0,Dropper:!0,Heater:!1,Lighter:!1,Reagent:!0,Stirrer:!0,WashBottle:!0},TestTube4={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,HeatTime:0,Name:"TestTube4",LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,
PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_TESTTUBE,Water:!1,Bath:!0,Centrifuge:!0,Dropper:!0,Heater:!1,Lighter:!1,Reagent:!0,Stirrer:!0,WashBottle:!0},Tv={Controls:null,Counter:null,Cursor:null,Handle:null,Menu:null,Log:null,Mode:TV_MODE_LOG,Panel:null,Player:null,PlayMode:TV_PLAYMODE_SINGLE,Video:null,VideoCur:0,VideoMax:0},WaterBath={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!0,
Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,HeatTime:0,Name:"Bath",LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:8,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperReaID:0,PaperID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_BEAKER,Water:!0,Bath:!1,Centrifuge:!1,Dropper:!1,Heater:!0,Lighter:!1,Reagent:!1,Stirrer:!1,WashBottle:!1,DockHole:[null,null,null,null]},WashBottle=
{AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,Burning:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,Name:"WashBottle",HeatTime:0,LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:5,LiqLvlMax:10,LiqOpac:.4,LiqDefOpac:.4,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_WASHBOTTLE,Water:!0,Bath:!1,Centrifuge:!1,Dropper:!1,Heater:!1,Lighter:!1,Reagent:!1,
Stirrer:!1,WashBottle:!1},WatchGlass={AnaAdspect:ADSPECT_SOLID,AnaID:0,AnaQty:0,Boiling:!1,CentTime:0,Clean:!1,Dock:null,Handle:null,Name:"WatchGlass",HeatTime:0,LiqAdspect:ADSPECT_LIQUID_NONE,LiqColor:null,LiqLvl:0,LiqLvlMax:5,LiqOpac:.5,LiqDefOpac:.5,OrgColor:null,PaperColor:null,PaperID:0,PaperReaID:0,PaperWater:!1,PosX:0,PosY:0,PosZ:0,ReaAdspect:[],ReaID:[],ReaNum:0,ReaQty:[],SmellID:SMELL_NONE,SolidColor:null,Stirred:!0,Type:GLASS_TYPE_WATCHGLASS,Water:!1,Bath:!1,Centrifuge:!1,Dropper:!0,Heater:!1,
Reagent:!0,Stirrer:!0,WashBottle:!0},$jscomp$compprop0={},Adspect2Id=($jscomp$compprop0[ADSPECT_PAPER]="#Solid-Paper",$jscomp$compprop0[ADSPECT_PLATE]="#Solid-Copper",$jscomp$compprop0[ADSPECT_POWDER]="#Solid",$jscomp$compprop0),GlassWare=[Beaker,Curcible,Dropper,Lighter,Nichrome,Stirrer,TestTube1,TestTube2,TestTube3,TestTube4,WaterBath,WatchGlass,WashBottle],TestTube=[TestTube1,TestTube2,TestTube3,TestTube4];
