var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};$jscomp.polyfill=function(a,b,d,c){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,c):$jscomp.polyfillUnisolated(a,b,d,c))};
$jscomp.polyfillUnisolated=function(a,b,d,c){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];if(!(e in d))return;d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,c){var e=a.split(".");a=1===e.length;c=e[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in c))return;c=c[g]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?c[e]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==d&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(c,e,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Math.sign",function(a){return a?a:function(b){b=Number(b);return 0===b||isNaN(b)?b:0<b?1:-1}},"es6","es3");PrefsLoad();
if(annyang){"it"==Lang?annyang.setLanguage("it-IT"):annyang.setLanguage("en-US");Prefs.SpeechRecActive&&annyang.start();annyang.debug(DEBUG);var ScCommands={};ScCommands[Msg.ScAbout]=ScAbout;ScCommands[Msg.ScAlexa]=function(){Speak(Msg.SsAlexa)};ScCommands[Msg.ScBunsenOx]=function(){BunsenOxidant(!0)};ScCommands[Msg.ScBunsenRed]=function(){BunsenOxidant(!1)};ScCommands[Msg.ScCent1Min]=function(){CentrifugeTime(1,!1)};ScCommands[Msg.ScCent2Min]=function(){CentrifugeTime(2,!1)};ScCommands[Msg.ScCent3Min]=
function(){CentrifugeTime(3,!1)};ScCommands[Msg.ScCent4Min]=function(){CentrifugeTime(4,!1)};ScCommands[Msg.ScClose+Msg.ScBunsenTap]=function(){BunsenGas(!1)};ScCommands[Msg.ScClose+Msg.ScCentrifuge]=function(){CentrifugeOpen(!1)};ScCommands[Msg.ScClose+Msg.ScMenu2]=ScClose;ScCommands[Msg.ScGoogle]=function(){Speak(Msg.SsGoogle)};ScCommands[Msg.ScGotoCentrifuge]=function(){GotoFootprint("PosCentrifuge")};ScCommands[Msg.ScGotoTV]=function(){GotoFootprint("PosTv")};ScCommands[Msg.ScGotoWork]=function(){GotoFootprint("PosWork")};
ScCommands[Msg.ScEmpty1]=ScTrashClick;ScCommands[Msg.ScEmpty2]=ScTrashClick;ScCommands[Msg.ScEmptyAll1]=ScTrashDblClick;ScCommands[Msg.ScEmptyAll2]=ScTrashDblClick;ScCommands[Msg.ScEmptyPaper]=ScTubePaperClick;ScCommands[Msg.ScHelp]=function(){Speak(Msg.SsHelp)};ScCommands[Msg.ScLeave1]=function(){ScGlassWareClick(null,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScBeaker]=function(){ScGlassWareClick(Beaker,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScCurcible]=function(){ScGlassWareClick(Curcible,
GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScDropper1]=function(){ScGlassWareClick(Dropper,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScDropper2]=function(){ScGlassWareClick(Dropper,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScLighter]=function(){ScGlassWareClick(Lighter,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScNichromeWire]=function(){ScGlassWareClick(Nichrome,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScStirrer]=function(){ScGlassWareClick(Stirrer,GLASS_CLICK_LEAVE)};
ScCommands[Msg.ScLeave2+Msg.ScTestTube]=function(){ScGlassWareClick(null,GLASS_CLICK_LEAVE,SCGWCLICK_TESTTUBEONLY)};ScCommands[Msg.ScLeave2+Msg.ScTestTube+Msg.ScNumber1]=function(){ScGlassWareClick(TestTube1,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScTestTube+Msg.ScNumber2]=function(){ScGlassWareClick(TestTube2,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScTestTube+Msg.ScNumber3]=function(){ScGlassWareClick(TestTube3,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScTestTube+Msg.ScNumber4]=
function(){ScGlassWareClick(TestTube4,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScLeave2+Msg.ScWatchGlass]=function(){ScGlassWareClick(WatchGlass,GLASS_CLICK_LEAVE)};ScCommands[Msg.ScMenu1]=ScMenu;ScCommands[Msg.ScMenuAna1]=ScMenuAna;ScCommands[Msg.ScMenuAna2]=ScMenuAna;ScCommands[Msg.ScMenuMain]=ScMenu;ScCommands[Msg.ScMenuSet1]=ScMenuSet;ScCommands[Msg.ScMenuSet2]=ScMenuSet;ScCommands[Msg.ScNotUnderstand1]=ScNotUnderstand;ScCommands[Msg.ScNotUnderstand2]=ScNotUnderstand;ScCommands[Msg.ScNotUnderstand3]=
ScNotUnderstand;ScCommands[Msg.ScOpen+Msg.ScCentrifuge]=function(){CentrifugeOpen(!0)};ScCommands[Msg.ScOpen+Msg.ScBunsenTap]=function(){BunsenGas(!0)};ScCommands[Msg.ScPut1+Msg.ScInCentrifuge]=function(){CentrifugePutTube(null)};ScCommands[Msg.ScPut1+Msg.ScInWaterBath]=ScBathClick;ScCommands[Msg.ScPut1+Msg.ScOnHeater]=ScHeaterClick;ScCommands[Msg.ScPut2+Msg.ScInCentrifuge]=function(){CentrifugePutTube(null)};ScCommands[Msg.ScPut2+Msg.ScInWaterBath]=ScBathClick;ScCommands[Msg.ScPut2+Msg.ScOnHeater]=
ScHeaterClick;ScCommands[Msg.ScPut3+Msg.ScInCentrifuge]=function(){CentrifugePutTube(null)};ScCommands[Msg.ScPut3+Msg.ScInWaterBath]=ScBathClick;ScCommands[Msg.ScPut3+Msg.ScOnHeater]=ScHeaterClick;ScCommands[Msg.ScSmell1]=ScSmellClick;ScCommands[Msg.ScSmell2+Msg.ScBeaker]=function(){ScSmellClick(Beaker)};ScCommands[Msg.ScSmell2+Msg.ScCurcible]=function(){ScSmellClick(Curcible)};ScCommands[Msg.ScSmell2+Msg.ScDropper1]=function(){ScSmellClick(Dropper)};ScCommands[Msg.ScSmell2+Msg.ScDropper2]=function(){ScSmellClick(Dropper)};
ScCommands[Msg.ScSmell2+Msg.ScStirrer]=function(){ScSmellClick(Stirrer)};ScCommands[Msg.ScSmell2+Msg.ScTestTube]=function(){ScSmellClick(TestTube)};ScCommands[Msg.ScSmell2+Msg.ScTestTube+Msg.ScNumber1]=function(){ScSmellClick(TestTube1)};ScCommands[Msg.ScSmell2+Msg.ScTestTube+Msg.ScNumber2]=function(){ScSmellClick(TestTube2)};ScCommands[Msg.ScSmell2+Msg.ScTestTube+Msg.ScNumber3]=function(){ScSmellClick(TestTube3)};ScCommands[Msg.ScSmell2+Msg.ScTestTube+Msg.ScNumber4]=function(){ScSmellClick(TestTube4)};
ScCommands[Msg.ScSmell2+Msg.ScWatchGlass]=function(){ScSmellClick(WatchGlass)};ScCommands[Msg.ScStop+Msg.ScCentrifuge]=function(){CentrifugeTime(0,!1)};ScCommands[Msg.ScSwitchOff+Msg.ScBunsen1]=function(){BunsenGas(!1)};ScCommands[Msg.ScSwitchOff+Msg.ScBunsen2]=function(){BunsenGas(!1)};ScCommands[Msg.ScSwitchOff+Msg.ScCentrifuge]=function(){CentrifugePower(!1)};ScCommands[Msg.ScSwitchOff+Msg.ScLight]=function(){ScLight(!1)};ScCommands[Msg.ScSwitchOff+Msg.ScTV]=function(){Speak(Msg.SsSwitchOffTV);
TvShowLog()};ScCommands[Msg.ScSwitchOn+Msg.ScBunsen1]=BunsenTurnOn;ScCommands[Msg.ScSwitchOn+Msg.ScBunsen2]=BunsenTurnOn;ScCommands[Msg.ScSwitchOn+Msg.ScCentrifuge]=function(){CentrifugePower(!0)};ScCommands[Msg.ScSwitchOn+Msg.ScLight]=function(){ScLight(!0)};ScCommands[Msg.ScSwitchOn+Msg.ScTV]=function(){Speak(Msg.SsSwitchOnTV);TvShowMenu()};ScCommands[Msg.ScTake+Msg.ScBeaker]=function(){ScGlassWareClick(Beaker,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScCurcible]=function(){ScGlassWareClick(Curcible,
GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScDropper1]=function(){ScGlassWareClick(Dropper,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScDropper2]=function(){ScGlassWareClick(Dropper,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScLighter]=function(){ScGlassWareClick(Lighter,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScNichromeWire]=function(){ScGlassWareClick(Nichrome,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScStirrer]=function(){ScGlassWareClick(Stirrer,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+
Msg.ScTestTube]=function(){ScGlassWareClick(TestTube1,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScTestTube+Msg.ScNumber1]=function(){ScGlassWareClick(TestTube1,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScTestTube+Msg.ScNumber2]=function(){ScGlassWareClick(TestTube2,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScTestTube+Msg.ScNumber3]=function(){ScGlassWareClick(TestTube3,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTake+Msg.ScTestTube+Msg.ScNumber4]=function(){ScGlassWareClick(TestTube4,GLASS_CLICK_TAKE)};
ScCommands[Msg.ScTake+Msg.ScWatchGlass]=function(){ScGlassWareClick(WatchGlass,GLASS_CLICK_TAKE)};ScCommands[Msg.ScTurn+Msg.ScBunsenRing]=function(){BunsenOxidant(!Bunsen.Ox)};ScCommands[Msg.ScUnlock+Msg.ScCentrifuge]=CentrifugeUnlock;ScCommands[Msg.ScUse+Msg.ScBeaker]=function(){ScGlassWareClick(Beaker,GLASS_CLICK_USE)};ScCommands[Msg.ScUse+Msg.ScCurcible]=function(){ScGlassWareClick(Curcible,GLASS_CLICK_USE)};ScCommands[Msg.ScUse+Msg.ScDropper1]=ScDropperUse;ScCommands[Msg.ScUse+Msg.ScDropper2]=
ScDropperUse;ScCommands[Msg.ScUseLighterBunsen1]=function(){ScLighterClick(Bunsen)};ScCommands[Msg.ScUseLighterBunsen2]=function(){ScLighterClick(Bunsen)};ScCommands[Msg.ScUseLighterCurcible]=function(){ScLighterClick(Curcible)};ScCommands[Msg.ScUseNichromeBunsen1]=function(){ScNichromeClick(Bunsen)};ScCommands[Msg.ScUseNichromeBunsen2]=function(){ScNichromeClick(Bunsen)};ScCommands[Msg.ScUseNichromeTube]=ScNichromeClick;ScCommands[Msg.ScUseNichromeTube1]=function(){ScNichromeClick(TestTube1)};ScCommands[Msg.ScUseNichromeTube2]=
function(){ScNichromeClick(TestTube2)};ScCommands[Msg.ScUseNichromeTube3]=function(){ScNichromeClick(TestTube3)};ScCommands[Msg.ScUseNichromeTube4]=function(){ScNichromeClick(TestTube4)};ScCommands[Msg.ScUse+Msg.ScNichromeWire]=ScNichromeClick;ScCommands[Msg.ScUse+Msg.ScSpatula]=ScSpatulaClick;ScCommands[Msg.ScUse+Msg.ScStirrer]=function(){ScGlassWareClick(Stirrer,GLASS_CLICK_USE)};ScCommands[Msg.ScUse+Msg.ScWashBottle]=ScWashBottleClick;ScCommands[Msg.ScUse+Msg.ScWatchGlass]=function(){ScGlassWareClick(WatchGlass,
GLASS_CLICK_USE)};annyang.addCommands(ScCommands)}else DEBUG&&console.log(LOG_PROMPT,"Speech recognition not supported"),Prefs.SpeechRecActive=!1,Prefs.SpeechRecAvail=!1;
function ShowEvent(){if(Voice)var a=setInterval(function(){var b=Voice.getVoices(),d=0;if(b.length){if("it"===Lang){d="it-IT";var c="it_IT"}else d="en-GB",c="en_GB";clearInterval(a);for(var e=0;e<b.length;++e)if(b[e].lang===d||b[e].lang===c)if(VoiceHandle=b[e],!IsEdge||-1!=VoiceHandle.name.indexOf("Elsa"))break;VoiceHandle?DEBUG&&console.log(LOG_PROMPT,"Selected voice synthesis",b[e].name+" ("+b[e].lang+")"):(DEBUG&&console.log(LOG_PROMPT,d+" voice not available"),Prefs.VoiceActive=!1,Prefs.VoiceAvail=
!1)}else 20<++d&&(DEBUG&&console.log(LOG_PROMPT,"Voices not available"),Prefs.VoiceActive=!1,Prefs.VoiceAvail=!1,clearInterval(a))},200);else"undefined"!==typeof responsiveVoice?(DEBUG&&console.log(LOG_PROMPT,"Using ResponsiveVoice"),"it"==Lang&&responsiveVoice.setDefaultRate(1.05),VoiceType=VOICE_TYPE_RESPONSIVE):IniGetBool("TTS","Avail")&&"PICO"===ServerIni.TTS.Type.toUpperCase()?(DEBUG&&console.log(LOG_PROMPT,"Using Pico TTS server"),"http"==ServerIni.TTS.URL.substring(0,4)?PicoTtsURI=ServerIni.TTS.URL:
(PicoTtsURI=document.location.href,PicoTtsURI=PicoTtsURI.substring(0,PicoTtsURI.lastIndexOf("/"))+ServerIni.TTS.URL),PicoTtsURI+="?lang="+Msg.PicoTtsLanguage+"&text=",VoiceType=VOICE_TYPE_PICOSERVER):(DEBUG&&console.log(LOG_PROMPT,"Voice synthesis not supported"),Prefs.VoiceActive=!1,Prefs.VoiceAvail=!1,VoiceType=VOICE_TYPE_NONE)}
AFRAME.registerComponent("scene-listener",{init:function(){Scene=document.querySelector("a-scene");Asset=Scene.querySelector("a-assets");Bunsen.Handle=Scene.querySelector("#Bunsen");Bunsen.FlameOxHandle=Bunsen.Handle.querySelector("#FlameOx");Camera=Scene.querySelector("#Camera");CameraRig=Scene.querySelector("#CameraRig");Centrifuge.Handle=Scene.querySelector("#Centrifuge");Centrifuge.hCover=Centrifuge.Handle.querySelector("#Cover");Centrifuge.hLedOpen=Centrifuge.Handle.querySelector("#LedOpen");
Centrifuge.hLedPower=Centrifuge.Handle.querySelector("#LedPower");Centrifuge.hPotSpeed=Centrifuge.Handle.querySelector("#PotSpeed");Centrifuge.hPotTime=Centrifuge.Handle.querySelector("#PotTime");Cursor=Scene.querySelector("#Cursor");DlgAbout=Scene.querySelector("#DlgAbout");DlgAnaCode=Scene.querySelector("#DlgAnaCode");DlgMenu=Scene.querySelector("#DlgMenu");DlgMenuAna=Scene.querySelector("#DlgMenuAna");DlgMenuSet=Scene.querySelector("#DlgMenuSet");Floor=Scene.querySelector("#Floor");Gui=Scene.querySelector("#Gui");
Heater.Handle=Scene.querySelector("#Heater");Lighter.Handle=Scene.querySelector("#Lighter");Rack=Scene.querySelector("#Rack");Spatula=Scene.querySelector("#Spatula");Shadow=Scene.querySelector("#Shadow");Trash=Scene.querySelector("#Trash");Tv.Handle=Scene.querySelector("#TV");Tv.Controls=Tv.Handle.querySelector("#TvControls");Tv.Counter=Tv.Controls.querySelector("#TvCounter");Tv.Cursor=Tv.Controls.querySelector("#TvCursor");Tv.Log=Tv.Handle.querySelector("#Log");Tv.Menu=Tv.Handle.querySelector("#Menu");
Tv.Panel=Tv.Controls.querySelector("#Panel");Tv.Player=Tv.Handle.querySelector("#Player");Tv.Video=Asset.querySelector("#TvVideo");Workbench=Scene.querySelector("#WorkBench");for(var a=0;6>a;a++)Centrifuge.hTube[a]=Centrifuge.Handle.querySelector("#Tube"+(a+1));for(a=0;a<GlassWare.length;++a){var b=GlassWare[a];b.Handle=Scene.querySelector("#"+b.Name);var d=b.Handle.getAttribute("position");b.PosX=d.x;b.PosY=d.y;b.PosZ=d.z}Heater.WhatGlass=WaterBath;WaterBath.Dock=Heater.Handle;b=Scene.querySelectorAll(".centnoshadow");
for(a=0;a<b.length;a++)DisableShadow(b[a],!1,!0);SetTextButton(DlgAbout,"#BT_Ok",Msg.BtOk);SetTextLabel(DlgAbout,"#LBL_Copyright","\u00a9"+LABSIM_COPYRIGHT+", Alessandro Pedretti");SetTextLabel(DlgAbout,"#LBL_Rights",Msg.DlgAboutRights);SetTextLabel(DlgAbout,"#LBL_SubTitle",Msg.DlgAboutSubTitle);SetTextLabel(DlgAbout,"#LBL_Version","LabSim "+LABSIM_VER);SetTextButton(DlgAnaCode,"#BT_CodeOk",Msg.DlgAnaCodeConfirm);SetTextLabel(DlgAnaCode,"#LBL_Title",Msg.DlgAnaCodeTitle);SetTextButton(DlgMenu,"#BT_About",
Msg.DlgMenuAbout);SetTextButton(DlgMenu,"#BT_Restart",Msg.DlgMenuRestart);SetTextButton(DlgMenu,"#BT_SelAna",Msg.DlgMenuAna);SetTextButton(DlgMenu,"#BT_Settings",Msg.DlgMenuSetTitle);SetTextLabel(DlgMenu,"#LBL_Title",Msg.DlgMenuTitle);SetTextLabel(DlgMenuAna,"#LBL_Title",Msg.DlgMenuAnaTitle);SetTextLabel(DlgMenuSet,"#LBL_Title",Msg.DlgMenuSetTitle);SetTextToggle(DlgMenuSet,"#TO_Detail",Msg.DlgMenuSetDetail);SetTextToggle(DlgMenuSet,"#TO_Sound",Msg.DlgMenuSetSound);SetTextToggle(DlgMenuSet,"#TO_SpeechRec",
Msg.DlgMenuSetSpeechRec);SetTextToggle(DlgMenuSet,"#TO_SpeechSynth",Msg.DlgMenuSetSpeechSynth);SetCheckToggle(DlgMenuSet,"#TO_Detail",Prefs.Detail);SetCheckToggle(DlgMenuSet,"#TO_Sound",Prefs.SoundActive);SetCheckToggle(DlgMenuSet,"#TO_SpeechRec",Prefs.SpeechRecActive);SetCheckToggle(DlgMenuSet,"#TO_SpeechSynth",Prefs.VoiceActive);LogPrint(Msg.LogWelcome+"\n");this.el.addEventListener("enter-vr",function(){if(Device&DEVICE_TYPE_VR){var c=CameraRig.getAttribute("position");CameraRig.setAttribute("position",
c.x+" "+(c.y-CameraRigOffsetY)+" "+c.z);CameraRigOffsetY=CAMERA_RIG_OFFY_VR;VrMode=!0}});this.el.addEventListener("exit-vr",function(){if(Device&DEVICE_TYPE_VR){CameraRigOffsetY=CAMERA_RIG_OFFY;VrMode=!1;var c=CameraRig.getAttribute("position");CameraRig.setAttribute("position",c.x+" "+(c.y+CameraRigOffsetY)+" "+c.z)}});window.addEventListener("keyup",function(c){DEBUG&&console.log(LOG_PROMPT,"Key up event",c.keyCode,c.ctrlKey);switch(c.keyCode){case 27:DlgClose(ShownDlgName);break;case 32:case 77:ScMenu()}},
{passive:!0});this.el.addEventListener("mousedown",function(c){RightMbPressed(c)&&(MouseTrans.x=c.clientX,MouseTrans.y=c.clientY,c=Camera.getAttribute("position"),MouseTrans.CameraPosX=c.x,MouseTrans.CameraPosY=c.y)});this.el.addEventListener("mousemove",function(c){if(RightMbPressed(c)){var e=MouseTrans.CameraPosX-(c.clientX-MouseTrans.x)/(Scene.clientWidth*Zoom*.5);c=MouseTrans.CameraPosY+(c.clientY-MouseTrans.y)/(Scene.clientHeight*Zoom*.5);e<CAMERA_MIN_X?e=CAMERA_MIN_X:e>CAMERA_MAX_X&&(e=CAMERA_MAX_X);
c<CAMERA_MIN_Y?c=CAMERA_MIN_Y:c>CAMERA_MAX_Y&&(c=CAMERA_MAX_Y);Camera.setAttribute("position",e+" "+c+" 0 ")}},{passive:!0});this.el.addEventListener("wheel",function(){Zoom=Math.min(Math.max(Zoom+.1*Math.sign(event.wheelDelta),.8),6);Camera.setAttribute("camera","zoom: "+Zoom)},{passive:!0});Tv.Video.addEventListener("ended",function(){switch(Tv.PlayMode){case TV_PLAYMODE_ALL:if(Tv.VideoCur<Tv.VideoMax){TvPlayVideo(++Tv.VideoCur);break}case TV_PLAYMODE_SINGLE:RaycastableObj(".tvctrlray",!1);VoiceRecEnable(!0);
TvShowMenu();break;case TV_PLAYMODE_LOOP:TvPlayVideo(Tv.VideoCur)}});Tv.Video.addEventListener("timeupdate",function(){Tv.Panel.getAttribute("visible")&&TvProgBarMove(Tv.Video.currentTime)});TvInit();SetDetail(Prefs.Detail);SetTextSplash(Msg.LoadingDb);LoadBinaryFile("db/LabSim.sqlite?ver="+LABSIM_VER,function(c){initSqlJs({locateFile:function(){return"dist/sql-wasm.wasm"}}).then(function(e){hDb=new e.Database(c);FillAnalytes();FillReagents();Device=DetectDevice();(Device&DEVICE_TYPE_DESKTOP||Device&
DEVICE_TYPE_VR)&&Scene.setAttribute("vr-mode-ui","enabled: true");document.getElementById("DivSplash").style.display="none";Scene.setAttribute("visible","true");HeatingThread();EnableSound(Prefs.SoundActive);setTimeout(function(){DisableShadowAll();DlgShow("DlgAbout")},500)})})}});
AFRAME.registerComponent("bath-listener",{init:function(){this.el.addEventListener("animationcomplete",function(a){"animation__L"==a.detail.name&&(WaterBath.Dock===Heater.Handle&&(Heater.WhatGlass=WaterBath),PlaySound(WaterBath.Handle.querySelector("#SND_Tick")))});this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&ScBathClick()})}});AFRAME.registerComponent("book-listener",{init:function(){this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&ScMenu()})}});
AFRAME.registerComponent("bunsen-listener",{init:function(){this.el.addEventListener("click",function(){if(MbClickID===MOUSE_BUTTON_LEFT)switch(this.id){case "BunsenBody":GlassReady.Obj===Lighter?ScLighterClick(Bunsen):ScNichromeClick(Bunsen);break;case "Tap":BunsenGas(!Bunsen.On);break;case "Ring":BunsenOxidant(!Bunsen.Ox)}})}});
AFRAME.registerComponent("centrifuge-listener",{init:function(){this.el.addEventListener("animationcomplete",function(a){"animation__Close"===a.detail.name&&setTimeout(function(){PlaySound(Centrifuge.hLedOpen.querySelector("#SND_Clack"));CentrifugeTime(Centrifuge.Time)},200)});this.el.addEventListener("click",function(){if(MbClickID===MOUSE_BUTTON_LEFT)switch(this){case Centrifuge.hCover:CentrifugeOpen(!Centrifuge.Open);break;case Centrifuge.hLedOpen:CentrifugeUnlock();break;case Centrifuge.hLedPower:CentrifugePower(!Centrifuge.On);
break;case Centrifuge.hPotSpeed:CentrifugeSpeed(Centrifuge.Speed+1);break;case Centrifuge.hPotTime:CentrifugeTime(Centrifuge.Time+1);break;case Centrifuge.hTube[0]:case Centrifuge.hTube[1]:case Centrifuge.hTube[2]:case Centrifuge.hTube[3]:case Centrifuge.hTube[4]:case Centrifuge.hTube[5]:CentrifugePutTube(this)}});this.el.addEventListener("sound-ended",function(){switch(this.id){case "SND_CentStart":PlaySound(Centrifuge.Handle.querySelector("#SND_CentRun"));break;case "SND_CentStop":CentrifugeStopEvent(),
Centrifuge.On&&PlaySound(Centrifuge.Handle.querySelector("#SND_Beep"))}})}});
AFRAME.registerComponent("dropper-listener",{init:function(){this.el.addEventListener("animationbegin",function(a){switch(a.detail.name){case "animation__1":PlaySound(this.querySelector("#SND_Pipette1"));break;case "animation__1d":PlayDrainSound(this,GlassTarget);if(GlassTarget.Type==GLASS_TYPE_TESTTUBE)switch(GlassTarget.PaperID){case REA_ID_PAPER:ColorPaperSet(GlassTarget,Dropper.LiqColor);GlassTarget.PaperReaID=Dropper.ReaID[0];GlassTarget.PaperWater=!0;return;case REA_ID_UNIVIND:ColorPaperSet(GlassTarget,
ColorFromPh(7));GlassTarget.PaperWater=!0;return}LiquidMove(GlassTarget,Dropper);GlassTarget.Water&&GlassPrecipitate(GlassTarget)&&GlassTarget.LiqAdspect!==ADSPECT_LIQUID_SUSP&&(GlassTarget.LiqAdspect=ADSPECT_LIQUID_SUSP,LiquidUpdate(GlassTarget));break;case "animation__2":PlaySound(this.querySelector("#SND_Pipette2")),LiquidMove(Dropper,GlassTarget)}})}});
AFRAME.registerComponent("glassware-listener",{init:function(){this.el.addEventListener("animationbegin",function(a){"animation__FlameTestE"==a.detail.name&&BunsenColor()});this.el.addEventListener("animationcomplete",function(a){switch(a.detail.name){case "animation__DockCent":AnimRunning=!1;GlassReady.Obj.Dock=Centrifuge.Handle;GlassReady.LeaveY-=1.05;ScGlassWareClick(GlassReady,GLASS_CLICK_LEAVE);break;case "animation__DockHeater":AnimRunning=!1;GlassReady.Obj.Dock=Heater.Handle;GlassReady.LeaveY+=
.09;Heater.WhatGlass=GlassReady.Obj;ScGlassWareClick(GlassReady,GLASS_CLICK_LEAVE);break;case "animation__DockRack":AnimRunning=!1;GlassReady.Obj.Dock=Rack;GlassReady.LeaveY+=.5;ScGlassWareClick(GlassReady,GLASS_CLICK_LEAVE);break;case "animation__FlameTestB":Bunsen.Burning&&Bunsen.Ox&&(BunsenColor(ColorFlameByMolID(Nichrome.AnaID)),Nichrome.CleanCount&&!--Nichrome.CleanCount&&(Nichrome.AnaID=0),Nichrome.ReaID=[],Nichrome.ReaNum=0);break;case "animation__Ign":if(GlassTarget.Type===GLASS_TYPE_BUNSEN)Bunsen.Timer<=
EXPLOSION_TIME&&BunsenBurn(!0);else if(GlassTarget.Type===GLASS_TYPE_CURCIBLE&&!GlassTarget.Water&&GlassTarget.ReaNum){var b=GlassTarget.ReaID.indexOf(REA_ID_CH3OH);-1!==b&&GlassTarget.ReaQty[b]>=REA_QTY_CH3OH_IGN&&setTimeout(function(){var d=GlassTarget.Handle.querySelector("#Flame");d.setAttribute("particle-system","color: "+ColorFlameByID(COLOR_ID_COLORLESS));d.setAttribute("particle-system","enabled: true");DisableShadowAll();GlassTarget.Burning=!0;Reaction(GlassTarget);var c=setInterval(function(){--Curcible.LiqLvl;
LiquidUpdate(Curcible);0===--GlassTarget.ReaQty[b]&&(d.setAttribute("particle-system","enabled: false"),DisableShadowAll(),Curcible.Burning=!1,ReaRemove(Curcible,b),clearInterval(c))},1E4)},1E3)}break;case "animation__L":AnimRunning=!1,GlassReady.Handle&&this==GlassReady.Handle||PlaySound(this.querySelector("#SND_Tick"))}});this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&ScGlassWareClick(GlassGetByHandle(this),GLASS_CLICK_TOGGLE)})}});
AFRAME.registerComponent("heater-listener",{init:function(){this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&ScHeaterClick()})}});
AFRAME.registerComponent("lighterbutton-listener",{init:function(){this.el.addEventListener("animationcomplete",function(a){switch(a.detail.name){case "animation__1":PlaySound(Lighter.Handle.querySelector("#SND_Lighter"));if(Bunsen.On&&!Bunsen.Burning&&Bunsen.Timer>EXPLOSION_TIME){Explosion();break}Lighter.Handle.querySelector("#Flame").setAttribute("particle-system","enabled: true");DisableShadowAll();break;case "animation__2":Lighter.Handle.querySelector("#Flame").setAttribute("particle-system",
"enabled: false"),DisableShadowAll()}})}});document.addEventListener("mousedown",function(a){MbClickID="button"in a?a.button:MOUSE_BUTTON_LEFT});AFRAME.registerComponent("position-listener",{init:function(){this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&GotoFootprint(this.id)})}});
AFRAME.registerComponent("rea-listener",{init:function(){this.el.addEventListener("movingended",function(){PlaySound(this.querySelector("#SND_ReaLiquidTok"))});this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&ScReagentClick(this)})}});AFRAME.registerComponent("reapipette-listener",{init:function(){this.el.addEventListener("animationcomplete",function(a){"animation__L"==a.detail.name&&(AnimRunning=!1)})}});
AFRAME.registerComponent("rearubber-listener",{init:function(){this.el.addEventListener("animationbegin",function(a){switch(a.detail.name){case "animation__1":PlaySound(this.querySelector("#SND_Pipette1"));break;case "animation__2":PlaySound(this.querySelector("#SND_Pipette2"));break;case "animation__6":PlayDrainSound(this),GlassReady.Obj.Type==GLASS_TYPE_TESTTUBE&&GlassReady.Obj.PaperID&&ColorPaperSet(GlassReady.Obj,GlassReady.Obj.PaperColor)}});this.el.addEventListener("click",function(a){MbClickID===
MOUSE_BUTTON_LEFT&&(ScReaPipetteClick(this),a.stopPropagation())})}});AFRAME.registerComponent("smell-listener",{init:function(){this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&ScSmellClick()})}});
AFRAME.registerComponent("spatula-listener",{init:function(){this.el.addEventListener("animationcomplete",function(a){switch(a.detail.name){case "animation__4":if(a=Spatula.querySelector(Adspect2Id[ReaReady.Adspect]))a.setAttribute("visible","true"),ReaReady.Adspect===ADSPECT_POWDER?ColorSet(a,GlassReady.SolidColor):ColorSet(a,ReaReady.Color);break;case "animation__7":var b=Adspect2Id[ReaReady.Adspect];if(a=GlassReady.Handle.querySelector(b))ReaReady.Adspect===ADSPECT_PAPER?(ColorPaperSet(GlassReady.Obj,
ReaReady.Color),GlassReady.Obj.Type===GLASS_TYPE_TESTTUBE&&a.object3D.position.set(0,TUBE_PAPER_POS_Y,0)):ColorSet(a,ReaReady.Color),a.setAttribute("visible","true");(a=Spatula.querySelector(b))&&a.setAttribute("visible","false");Reaction(GlassReady.Obj);break;case "animation__L":AnimRunning=!1,PlaySound(this.querySelector("#SND_Tick"))}});this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&ScSpatulaClick()})}});
AFRAME.registerComponent("tubepaper-listener",{init:function(){this.el.addEventListener("animationcomplete",function(a){switch(a.detail.name){case "animation__L":a=$jscomp.makeIterator(TestTube);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.Handle.querySelector("#Solid-Paper")===this){GlassEmpty(b,EMPTY_PAPER);break}AnimRunning=!1}});this.el.addEventListener("click",function(a){if(MbClickID===MOUSE_BUTTON_LEFT){for(var b=$jscomp.makeIterator(TestTube),d=b.next();!d.done;d=b.next())if(d=d.value,
d.Handle.querySelector("#Solid-Paper")===this){ScTubePaperClick(d);break}a.stopPropagation()}})}});
AFRAME.registerComponent("tv-listener",{init:function(){this.el.addEventListener("click",function(a){if(MbClickID===MOUSE_BUTTON_LEFT)switch(DEBUG&&console.log(LOG_PROMPT,"TV click",Tv.Mode,this.id),Tv.Mode){case TV_MODE_LOG:VoiceRecEnable(!0);TvShowMenu();break;case TV_MODE_PLAYER:switch(this.id){case "TvNext":Tv.VideoCur<Tv.VideoMax&&TvPlayVideo(++Tv.VideoCur);break;case "TvPause":Tv.Video.paused?(VoiceRecEnable(!1),Tv.Video.play()):(Tv.Video.pause(),VoiceRecEnable(!0));break;case "TvPlay":VoiceRecEnable(!1);
Tv.Video.play();break;case "TvPlayMode":Tv.PlayMode==TV_PLAYMODE_SINGLE?Tv.PlayMode=0:++Tv.PlayMode;Tv.Controls.querySelector("#TvPlayMode").setAttribute("src","#TvBtPmode"+Tv.PlayMode);break;case "TvPrev":0<Tv.VideoCur&&TvPlayVideo(--Tv.VideoCur);break;case "TvProgBar":a=Tv.Video.duration*(this.object3D.worldToLocal(a.detail.intersection.point).x-TV_PROGBAR_OFFSET_X)/TV_PROGBAR_WIDTH;DEBUG&&console.log(LOG_PROMPT,"Move video to",a);Tv.Video.currentTime=a;TvProgBarMove(a);break;case "TvStop":Tv.Video.pause();
Tv.Video.currentTime=0;RaycastableObj(".tvctrlray",!1);VoiceRecEnable(!0);TvShowMenu();break;default:Tv.Panel.getAttribute("visible")||(Tv.Video.paused?(VoiceRecEnable(!1),Tv.Video.play()):(Tv.Video.pause(),VoiceRecEnable(!0)))}}})}});AFRAME.registerComponent("trash-listener",{init:function(){this.el.addEventListener("click",function(a){MbClickID===MOUSE_BUTTON_LEFT&&DoubleClick(ScTrashClick,ScTrashDblClick)})}});
AFRAME.registerComponent("washbottle-listener",{init:function(){this.el.addEventListener("animationcomplete",function(a){switch(a.detail.name){case "animation__4":PlayDrainSound(this);if(GlassReady.Obj.Type==GLASS_TYPE_TESTTUBE)switch(GlassReady.Obj.PaperID){case REA_ID_PAPER:GlassReady.Obj.PaperWater=!0;return;case REA_ID_UNIVIND:ColorPaperSet(GlassReady,ColorFromPh(7));GlassReady.Obj.PaperWater=!0;return}LiquidMove(GlassReady.Obj,WashBottle);break;case "animation__L":AnimRunning=!1,PlaySound(this.querySelector("#SND_Tunk"))}});
this.el.addEventListener("click",function(){MbClickID===MOUSE_BUTTON_LEFT&&ScWashBottleClick()})}});
