function AnaCodeClick(a){var b=a.getAttribute("Id").slice(7);DEBUG&&console.log(LOG_PROMPT,"Key pressed",b);var c=DlgAnaCode.querySelector("#LBL_Code");(a=c.getAttribute("value"))||(a="");switch(b){case "Ca":a="";break;case "Bs":a&&(a=a.slice(0,-1));break;case "Ok":if(a)if(a.length===CODE_LENGTH){b=parseInt("0x"+a);c=(b&16711680)>>16^CODE_INTK;var d=(b&65280)>>8^CODE_INTK^c,f=b&255^CODE_INTK^c;b=c+d;255<b&&(b-=255);DEBUG&&console.log(LOG_PROMPT,"Analyte code\nEncKey:",c,"\nAnaID:",d,"\nCrc:",f,"\nCrc calc:",
b);if(f!==b){ShowError(Msg.SsAnaCodeInvalid);return}b=hDb.prepare("SELECT MoleculeID FROM Molecules WHERE (Analyte AND MoleculeID = "+d+");");b.step()?(ShowError(Msg.SsAnaCodeOk+" "+a+". "+Msg.SsAnaCodeReady),AnalyteID=d,DlgClose("DlgAnaCode")):ShowError(Msg.SsAnaCodeInvalid);b.free()}else ShowError(Msg.SsAnaCodeTooShort);else ShowError(Msg.SsAnaCodeEmpty);return;default:a.length<CODE_LENGTH&&(a+=b)}c.setAttribute("value",a)}
function CreateGuiButton(a,b,c,d,f,g,h){var e=document.createElement("a-gui-button");e.setAttribute("class","guiray");e.setAttribute("id",b);e.setAttribute("width","1.16");e.setAttribute("height",MENUANA_BUTTON_HEIGHT);e.setAttribute("font-size","72px");e.setAttribute("sound","src: #SndClick; on: click");e.setAttribute("value",c);e.setAttribute("margin",h+" 0 0.05 "+g);e.setAttribute("onclick","ScMenuAnaClick(this)");d&&e.setAttribute("background-color",d);d&&e.setAttribute("hover-color",f);a.appendChild(e);
return e}
function DlgClose(a){if(a){var b=Gui.querySelector("#"+a);b.getAttribute("visible")&&("DlgMenuSet"==a&&PrefsSave(),Gui.setAttribute("animation","dur: "+GUI_FADETIME+"; property: position; from: "+GUI_POS_VISIBLE+"; to: "+GUI_POS_INVISIBLE+"; easing: easeInOutQuad"),setTimeout(function(){b.setAttribute("visible",!1);var c=b.getAttribute("position");b.setAttribute("position",c.x+" "+c.y+" 0");c=b.querySelectorAll(".guiray");for(var d=0;d<c.length;d++)c[d].removeAttribute("menuray")},GUI_FADETIME),ShownDlgName=
"")}}function DlgShow(a,b){ShownDlgName?ShownDlgName!=a&&(DlgClose(ShownDlgName),setTimeout(function(){DlgShowInt(a,b)},GUI_FADETIME)):DlgShowInt(a,b)}
function DlgShowInt(a,b){var c=Gui.querySelector("#"+a),d=c.getAttribute("position");c.setAttribute("visible",!0);c.setAttribute("position",d.x+" "+d.y+" 0.1");Gui.setAttribute("animation","dur: "+GUI_FADETIME+"; property: position; from: "+GUI_POS_INVISIBLE+"; to: "+GUI_POS_VISIBLE+"; easing: easeInOutQuad");c=c.querySelectorAll(".guiray");for(d=0;d<c.length;d++)c[d].setAttribute("menuray");ShownDlgName=a;Speak(b)}function ScAbout(){DlgShow("DlgAbout")}function ScClose(){DlgClose(ShownDlgName)}
function ScLight(a){Light==a?Speak(a?Msg.SsLightAlreadyOn:Msg.SsLightAlreadyOff):(Light=a,Speak(a?Msg.SsSwitchOnLight:Msg.SsSwitchOffLight,function(){PlaySound("SND_Switch");Scene.querySelector("#LightAmbient").setAttribute("visible",a)}))}function ScMenu(){DlgShow("DlgMenu",Msg.DlgMenuTitle)}function ScMenuAna(){DlgShow("DlgMenuAna",Msg.DlgMenuAnaTitle)}
function ScMenuAnaClick(a){a=a.getAttribute("Id").slice(6);if("Code"===a)DlgShow("DlgAnaCode",Msg.DlgAnaCodeTitle);else{var b="SELECT Molecules.MoleculeID, Molecules.Formula, "+Msg.SqlMolName+" FROM Molecules WHERE (Molecules.Analyte";switch(a){case "RndAll":b+=")";break;case "RndInsol":b+=" AND NOT Molecules.SolWater)";break;case "RndSol":b+=" AND Molecules.SolWater)";break;default:AnalyteID=a,b+=" AND Molecules.MoleculeID = "+AnalyteID+")"}hDb.each(b+" ORDER BY RANDOM() LIMIT 1;",function(c){AnalyteID=
c.MoleculeID;var d=Msg.SsSubstToAnalize+" "+c[Msg.SqlMolName];LogPrint(d);Speak(d);DEBUG&&console.log(LOG_PROMPT,"Selected analyte",AnalyteID,c.Formula,c[Msg.SqlMolName])});DlgClose("DlgMenuAna")}}function ScMenuRestart(){DlgClose(ShownDlgName);setTimeout(function(){location.reload(!0)},1E3)}function ScMenuSet(){DlgShow("DlgMenuSet",Msg.DlgMenuSetTitle)}
function ScMenuSetDetail(){Prefs.Detail=DlgMenuSet.querySelector("#TO_Detail").getAttribute("gui-toggle").checked;Prefs.Changed=!0;SetDetail(Prefs.Detail)}function ScMenuSetSound(){Prefs.SoundActive=DlgMenuSet.querySelector("#TO_Sound").getAttribute("gui-toggle").checked;Prefs.Changed=!0;EnableSound(Prefs.SoundActive)}
function ScMenuSetSpeechRec(){Prefs.SpeechRecAvail&&(Prefs.SpeechRecActive=DlgMenuSet.querySelector("#TO_SpeechRec").getAttribute("gui-toggle").checked,Prefs.Changed=!0,Prefs.SpeechRecActive?annyang.start():annyang.abort())}function ScMenuSetSpeechSynth(){Prefs.VoiceAvail&&(Prefs.VoiceActive=DlgMenuSet.querySelector("#TO_SpeechSynth").getAttribute("gui-toggle").checked,Prefs.Changed=!0)}function ScNotUnderstand(){Speak(Msg.SsNotUnderstand1)}
function SetTextButton(a,b,c){a=a.querySelector(b);a.setAttribute("value",c);a.components["gui-button"].setText(c)}function SetTextLabel(a,b,c){a.querySelector(b).setAttribute("value",c)}function SetTextRadio(a,b,c){a=a.querySelector(b);b=a.components["gui-radio"];a.setAttribute("value",c);drawText(b.ctxLabel,b.labelCanvas,c,b.data.fontSize,b.data.fontFamily,b.data.fontColor,1,"left","middle")}
function SetTextToggle(a,b,c){a=a.querySelector(b);b=a.components["gui-toggle"];a.setAttribute("value",c);drawText(b.ctxLabel,b.labelCanvas,c,b.data.fontSize,b.data.fontFamily,b.data.fontColor,1,"left","middle")};
