var AmbientValMtx=[0,4,8,2,-4,-2],AMB_BUFFERCONC=4,AMB_DILEFFECT=6;
function GetAmbientForSolubility(a){switch(a.ReaNum){case 0:return REA_TYPE_UNKNOWN;case 1:var b=GetReaTypeByID(a.ReaID[0]);if(b===REA_TYPE_BUFFER)switch(a.ReaID[0]){case REA_ID_BUFFER_PH5:return REA_TYPE_ACIDWEAK;case REA_ID_BUFFER_PH9:return REA_TYPE_BASEWEAK;default:return REA_TYPE_UNKNOWN}else if(b>REA_TYPE_BASEWEAK)return REA_TYPE_UNKNOWN}if(1<a.ReaNum){var g=0,d=0,f=0,h=0,p=0;for(b=0;b<a.ReaNum;++b)if(a.ReaAdspect[b]===ADSPECT_LIQUID){var t=GetReaTypeByID(a.ReaID[b]);t<=REA_TYPE_BASEWEAK?(h+=
a.ReaQty[b],p+=a.ReaQty[b]*AmbientValMtx[t]):t===REA_TYPE_BUFFER&&(g=a.ReaID[b],f+=a.ReaQty[b]*AMB_BUFFERCONC,++d)}if(1===d)if(g===REA_ID_BUFFER_PH5){if(Math.abs(p)<=f)return REA_TYPE_ACIDWEAK}else{if(Math.abs(p)<=f)return REA_TYPE_BASEWEAK}else if(2===d&&Math.abs(p)<f)return REA_TYPE_UNKNOWN}else h=a.ReaQty[0],p=AmbientValMtx[b]*h;h?(p/=h,1<a.LiqLvl&&0<p&&(p/=1+a.LiqLvl/AMB_DILEFFECT),b=p>AmbientValMtx[REA_TYPE_ACIDSTRONG]?REA_TYPE_ACIDSTRONGCO:p>AmbientValMtx[REA_TYPE_ACIDWEAK]?REA_TYPE_ACIDSTRONG:
0<p?REA_TYPE_ACIDWEAK:p>=AmbientValMtx[REA_TYPE_BASEWEAK]?REA_TYPE_BASEWEAK:REA_TYPE_BASESTRONG):b=REA_TYPE_UNKNOWN;return b}function GetEventByID(a){if(!a)return null;var b;a=hDb.prepare("SELECT "+Msg.SqlEvent+" FROM Events WHERE (EventID="+a+");");a.step()&&(b=a.getAsObject()[Msg.SqlEvent]);a.free();return b}
function GetIonID(a,b){var g=0,d=["AnionID","CationID1","CationID2"];a=hDb.prepare("SELECT "+d[b]+" FROM Molecules WHERE (MoleculeID="+a+");");a.step()&&(g=a.getAsObject()[d[b]]);a.free();return g}function GetIonFormulaByID(a){if(!a)return null;a=hDb.prepare("SELECT Formula FROM Ions WHERE (IonID="+a+");");if(a.step())var b=a.getAsObject().Formula;a.free();return b}
function GetIonPh(a){var b=PHID_ND;a&&(a=hDb.prepare("SELECT pHs.pHVal FROM pHs INNER JOIN Ions ON pHs.pHID = Ions.pHID WHERE (Ions.IonID="+a+");"),a.step()&&(b=a.getAsObject().pHVal),a.free());return b}function GetIonPhID(a){var b=PHID_ND;a&&(a=hDb.prepare("SELECT pHs.pHID FROM pHs INNER JOIN Ions ON pHs.pHID = Ions.pHID WHERE (Ions.IonID="+a+");"),a.step()&&(b=a.getAsObject().pHID),a.free());return b}
function GetMixPh(a){if(a.AnaID&&a.AnaAdspect===ADSPECT_LIQUID){var b=GetMolPh(a.AnaID);var g=1}else g=b=0;for(var d=!1,f=0;f<a.ReaNum;++f)if(a.ReaAdspect[f]===ADSPECT_LIQUID){var h=a.ReaID[f];switch(h){case REA_ID_BUFFER_PH5:d=!0;b=5;g=1;continue;case REA_ID_BUFFER_PH9:d=!0;b=9;g=1;continue;case REA_ID_H2SO4_CONC:case REA_ID_HCL_6M:case REA_ID_HCL_CONC:d=!0;g=b=1;continue}if(!d){h=hDb.prepare("SELECT Reagents.MoleculeID1, Reagents.MoleculeID2, Reagents.MoleculeID3 FROM Reagents WHERE (Reagents.ReagentID="+
h+");");if(h.step())for(var p=h.getAsObject(),t=1;3>=t;++t){var l=p["MoleculeID"+t];l&&(l=GetMolPh(l),7!==l&&(b+=l,++g))}h.free()}}return b?b/g:7}function GetMolIDByFormula(a){if(!a)return 0;a=hDb.prepare('SELECT MoleculeID FROM Molecules WHERE (Formula = "'+a+'");');if(a.step())var b=a.getAsObject().MoleculeID;a.free();return b}function GetMolPh(a){if(!a)return 7;for(var b=0,g=0,d=0;3>d;++d){var f=GetIonPh(GetIonID(a,d));7!==f&&(b+=f,++g)}return b?b/g:7}
function GetMolPhID(a){if(!a)return PHID_NEUTRAL;for(var b=PHID_NEUTRAL,g=0;3>g;++g){var d=GetIonPhID(GetIonID(a,g));if(d!==PHID_ND)if(b===PHID_NEUTRAL)b=d;else if(b===PHID_5&&d===PHID_8to10||b===PHID_8to10&&d===PHID_5)b=PHID_NEUTRAL}return b}function GetReaLabelByID(a){if(!a)return null;var b;a=hDb.prepare("SELECT "+Msg.SqlReagent+" FROM Reagents WHERE (ReagentID="+a+");");a.step()&&(b=a.getAsObject()[Msg.SqlReagent]);a.free();return b}
function GetReaTypeByID(a){var b=REA_TYPE_UNKNOWN;a=hDb.prepare("SELECT ReagentTypeID FROM Reagents WHERE (ReagentID = "+a+");");a.step()&&(b=a.getAsObject().ReagentTypeID);return b}function GetSmellByID(a){a||(a=SMELL_NONE);var b;a=hDb.prepare("SELECT "+Msg.SqlSmell+" FROM Smells WHERE (SmellID="+a+");");a.step()&&(b=a.getAsObject()[Msg.SqlSmell]);a.free();return b}
function Reaction(a){DEBUG&&console.log(LOG_PROMPT,"Reaction","\nGlassware:",a.Name,"\nStirred:",a.Stirred,"\nHeat:",a.HeatTime,"\nWater:",a.Water);if(!GlassIsEmpty(a)){var b=[null,null],g=[0,0],d=[EVENT_NONE,EVENT_NONE],f=[0,0],h=SMELL_NONE,p=[0,0,0],t=a.LiqAdspect,l,m,e;if(a.Water||-1!==a.ReaID.indexOf(REA_ID_CH2CL2)){var q=GetAmbientForSolubility(a),u=null;if(a.AnaID){var n=a.AnaAdspect===ADSPECT_SOLID||a.AnaAdspect===ADSPECT_POWDER?SOLGRADE_INSOL:SOLGRADE_FULL;if(a.Stirred&&!a.ReaNum){var c=hDb.prepare("SELECT SolWater FROM Molecules WHERE (MoleculeID = "+
a.AnaID+");");if(!c.step()){DEBUG&&console.log(LOG_PROMPT,"Unable to get the solubility for AnaID = ",a.AnaID);c.free();return}c.getAsObject().SolWater&&(n=SOLGRADE_FULL);c.free()}if(n!==SOLGRADE_FULL){for(e=0;e<a.ReaNum;++e){c=hDb.prepare("SELECT SolGradeID, EventID1, ColorID1, EventID2, ColorID2, SmellID FROM Solubilities WHERE (Solubilities.MoleculeID = "+a.AnaID+" AND Solubilities.ReagentTypeID "+(q===REA_TYPE_UNKNOWN?"IS NULL":"= "+q)+" AND ReagentID = "+a.ReaID[e]+");");if(c.step()&&(b[0]=ColorByID(c.getAsObject().ColorID1),
b[1]=ColorByID(c.getAsObject().ColorID2),d[0]=c.getAsObject().EventID1,d[1]=c.getAsObject().EventID2,h=c.getAsObject().SmellID,n=c.getAsObject().SolGradeID,n===SOLGRADE_FULL)){c.free();break}c.free()}n!==SOLGRADE_FULL&&(c=hDb.prepare("SELECT SolGradeID, EventID1, ColorID1, EventID2, ColorID2, SmellID FROM Solubilities WHERE (Solubilities.MoleculeID = "+a.AnaID+" AND Solubilities.ReagentTypeID "+(q===REA_TYPE_UNKNOWN?"IS NULL":"= "+q)+");"),c.step()&&(b[0]=ColorByID(c.getAsObject().ColorID1),b[1]=
ColorByID(c.getAsObject().ColorID2),d[0]=c.getAsObject().EventID1,d[1]=c.getAsObject().EventID2,h=c.getAsObject().SmellID,n=c.getAsObject().SolGradeID),c.free());if(!a.Stirred){for(l=0;2>l;++l)if(d[l]===EVENT_EFFERV||d[l]===EVENT_EFFERVSLIGHT){a.Stirred=!0;Reaction(a);return}a.AnaAdspect===ADSPECT_SOLID&&n===SOLGRADE_FULL&&(n=SOLGRADE_INSOL)}}n===SOLGRADE_FULL?(a.AnaAdspect=ADSPECT_LIQUID,t=ADSPECT_LIQUID_NONE):a.AnaAdspect!==ADSPECT_SOLID&&(a.AnaAdspect=ADSPECT_SOLID,t=ADSPECT_LIQUID_SUSP);DEBUG&&
console.log(LOG_PROMPT,"Analyte solubility grade",n,void 0,void 0)}for(m=0;m<a.ReaNum;++m)if(a.ReaAdspect[m]===ADSPECT_SOLID||a.ReaAdspect[m]===ADSPECT_POWDER){var v=ReaId2AnaId(a.ReaID[m]);n=SOLGRADE_INSOL;if(a.ReaID[m]!==REA_ID_DUMMYINSOL){if(a.Stirred&&1===a.ReaNum){c=hDb.prepare("SELECT SolWater, ColorID FROM Molecules WHERE (MoleculeID = "+v+");");if(!c.step()){DEBUG&&console.log(LOG_PROMPT,"Unable to get the solubility for ReaID =",a.ReaID[m],"MolID =",v);c.free();continue}c.getAsObject().SolWater&&
(n=SOLGRADE_FULL,b[0]=ColorByID(c.getAsObject().ColorID),c.free())}if(n!==SOLGRADE_FULL){c=hDb.prepare("SELECT SolGradeID, EventID1, ColorID1, EventID2, ColorID2, SmellID FROM Solubilities WHERE (Solubilities.MoleculeID = "+v+" AND Solubilities.ReagentTypeID "+(q===REA_TYPE_UNKNOWN?"IS NULL":"= "+q)+");");if(c.step()&&(n=c.getAsObject().SolGradeID)&&(b[0]=ColorByID(c.getAsObject().ColorID1),b[1]=ColorByID(c.getAsObject().ColorID2),d[0]=c.getAsObject().EventID1,d[1]=c.getAsObject().EventID2,h=c.getAsObject().SmellID,
!a.Stirred)){for(l=0;2>l;++l)if(d[l]===EVENT_EFFERV||d[l]===EVENT_EFFERVSLIGHT){a.Stirred=!0;Reaction(a);return}n=SOLGRADE_INSOL}c.free()}}n===SOLGRADE_FULL?(l=ColorByMolID(v),a.ReaAdspect[m]=ADSPECT_LIQUID,l!==COLOR_WHITE&&(a.LiqColor=a.LiqColor&&a.LiqColor!==COLOR_WHITE?ColorBlend(a.LiqColor,l,.5):l)):a.ReaAdspect[m]!==ADSPECT_POWDER&&a.ReaAdspect[m]!==ADSPECT_SOLID&&(a.ReaAdspect[m]=ADSPECT_SOLID,t=ADSPECT_LIQUID_SUSP);DEBUG&&console.log(LOG_PROMPT,"Reactive ID",a.ReaID[m],"solubility grade",n,
d[0],d[1])}for(m=0;m<a.ReaNum;++m)(e=ReaId2SmellId(a.ReaID[m]))!==SMELL_NONE&&(h=h===SMELL_NONE?e:SMELL_UNKNOWN);h!==SMELL_NONE&&(a.SmellID=a.SmellID===SMELL_NONE?h:SMELL_UNKNOWN);DEBUG&&console.log(LOG_PROMPT,"Solution smell:",GetSmellByID(a.SmellID));if((l=a.AnaID)&&a.AnaAdspect===ADSPECT_LIQUID&&a.ReaNum)for(m=0;3>m;++m)if(IonID=GetIonID(l,m)){switch(a.ReaNum){case 1:c=ReactionQueryA1R(a,IonID,q);break;case 2:c=ReactionQueryA2R(a,IonID,q);break;case 3:h=-1;for(e=0;e<a.ReaNum;++e)if(a.ReaID[e]===
REA_ID_BUFFER_PH5){if(h=e,q!==REA_TYPE_ACIDWEAK)break}else if(a.ReaID[e]===REA_ID_BUFFER_PH9&&(h=e,q!==REA_TYPE_BASEWEAK))break;c=null;if(-1===h){for(e=v=n=0;e<a.ReaNum;++e)h=GetReaTypeByID(a.ReaID[e]),h<=REA_TYPE_BASEWEAK&&(n+=a.ReaQty[e],v+=a.ReaQty[e]*AmbientValMtx[h]);if(n)if(v/=n){for(e=0;e<a.ReaNum;++e)if(h=GetReaTypeByID(a.ReaID[e]),0<v){if(h===REA_TYPE_BASESTRONG||h===REA_TYPE_BASEWEAK)break}else if(h===REA_TYPE_ACIDSTRONG||h===REA_TYPE_ACIDSTRONGCO)break;e<a.ReaNum&&(c=ReactionQueryA3R1E(a,
IonID,q,e))}else{n=[];for(e=0;e<a.ReaNum;++e)h=GetReaTypeByID(a.ReaID[e]),h>REA_TYPE_BASEWEAK&&n.push(a.ReaID[e]);switch(n.length){case 1:c=ReactionQueryA1R(a,IonID,q,n[0]);break;case 2:c=ReactionQueryA2R(a,IonID,q,n[0],n[1])}}}else{if(e===a.ReaNum)for(e=0;e<a.ReaNum&&!(h=GetReaTypeByID(a.ReaID[e]),h>REA_TYPE_UNKNOWN&&h<=REA_TYPE_BASEWEAK);++e);e<a.ReaNum&&(c=ReactionQueryA3R1E(a,IonID,q,e))}c||(c=ReactionQueryA3R(a,IonID))}if(c.step()){(e=c.getAsObject().ProductID1)&&(f[0]=e);(e=c.getAsObject().ProductID2)&&
!f[1]&&(f[1]=e);(e=c.getAsObject().SolutionColorID)&&(u=u?ColorBlend(u,ColorByID(e)):ColorByID(e));(e=c.getAsObject().ColorID1)&&(b[0]=b[0]?ColorBlend(b[0],ColorByID(e)):ColorByID(e));(e=c.getAsObject().ColorID2)&&(b[1]=b[1]?ColorBlend(b[1],ColorByID(e)):ColorByID(e));if((e=c.getAsObject().EventID1)&&!d[0]||d[0]===EVENT_CLEAR_SOL)d[0]=e;if((e=c.getAsObject().EventID2)&&!d[1]||d[1]===EVENT_CLEAR_SOL)d[1]=e;(e=c.getAsObject().SmellID)&&e!==SMELL_NONE&&(a.SmellID=e);(e=c.getAsObject().GlasswareID1)&&
(p[m]=e);f[0]&&a.AnaID!==f[0]&&(f[0]===MOLID_FENOSO4?(h=a.ReaID.indexOf(REA_ID_FESO4),a.ReaQty[h]/a.LiqLvl>=REA_RINGTEST_FECONC?a.AnaID=f[0]:DEBUG&&console.log(LOG_PROMPT,"WARNING: FeSO4 not enough concentrated")):f[0]!==MOLID_CO2&&(a.AnaID=f[0]),a.AnaAdspect=ADSPECT_LIQUID);DEBUG&&console.log(LOG_PROMPT,"Reaction ID",c.getAsObject().TestID,"between analyte and reagents\n",GetIonFormulaByID(IonID),"+",GetReaLabelByID(a.ReaID[0]),"+",GetReaLabelByID(a.ReaID[1]),"+",GetReaLabelByID(a.ReaID[2]),"->",
GetMolFormulaByID(f[0]),"+",GetMolFormulaByID(f[1]),"\nEvents:",GetEventByID(d[0]),",",GetEventByID(d[1]),"\nSmell:",GetSmellByID(a.SmellID))}c.free()}if(a.ReaNum&&a.AnaID===l){m=0;do{e=m+1;do{if(c=1===a.ReaNum?a.PaperID===REA_ID_UNIVIND&&a.Type===GLASS_TYPE_TESTTUBE&&a.PaperWater?ReactionQuery2R(a):null:ReactionQuery2R(a,a.ReaID[m],a.ReaID[e]))c.step()&&(f[0]=c.getAsObject().ProductID1,f[0]&&(u=ColorByID(c.getAsObject().SolutionColorID),b[0]=ColorByID(c.getAsObject().ColorID1),b[1]=ColorByID(c.getAsObject().ColorID2),
d[0]=c.getAsObject().EventID1,d[1]=c.getAsObject().EventID2,f[1]=c.getAsObject().ProductID2,h=c.getAsObject().SmellID,p[0]=c.getAsObject().GlasswareID1,h&&h!==SMELL_NONE&&(a.SmellID=h),f[0]&&a.AnaID!==f[0]&&(f[0]===MOLID_FENOSO4?(h=a.ReaID.indexOf(REA_ID_FESO4),a.ReaQty[h]/a.LiqLvl>=REA_RINGTEST_FECONC?a.AnaID=f[0]:DEBUG&&console.log(LOG_PROMPT,"WARNING: FeSO4 not enough concentrated")):a.AnaID=f[0],a.AnaAdspect=ADSPECT_LIQUID),DEBUG&&console.log(LOG_PROMPT,"Reaction ID",c.getAsObject().TestID,"between 2 reagents\n",
GetReaLabelByID(a.ReaID[0]),"+",GetReaLabelByID(a.ReaID[1]),"->",GetMolFormulaByID(f[0]),"+",GetMolFormulaByID(f[1]),"\nEvents:",GetEventByID(d[0]),",",GetEventByID(d[1]),"\nSmell:",GetSmellByID(a.SmellID)))),c.free();++e}while(e<a.ReaNum);++m}while(m<a.ReaNum-1)}}else{if(a.AnaID){if(l=a.AnaID,a.ReaNum)for(l=a.AnaID,m=0;3>m;++m)if(IonID=GetIonID(l,m)){switch(a.ReaNum){case 1:c=ReactionQueryA1R(a,IonID);break;case 2:c=ReactionQueryA2R(a,IonID);break;case 3:c=ReactionQueryA3R(a,IonID)}if(c.step()){(e=
c.getAsObject().ProductID1)&&!f[0]&&(f[0]=e);(e=c.getAsObject().ProductID2)&&!f[1]&&(f[1]=e);(e=c.getAsObject().SolutionColorID)&&(u=u?ColorBlend(u,ColorByID(e)):ColorByID(e));g[0]=c.getAsObject().ColorID1;e&&(b[0]=b[0]?ColorBlend(b[0],ColorByID(g[0])):ColorByID(g[0]));g[1]=c.getAsObject().ColorID2;e&&(b[1]=b[1]?ColorBlend(b[1],ColorByID(g[1])):ColorByID(g[1]));if((e=c.getAsObject().EventID1)&&!d[0]||d[0]===EVENT_CLEAR_SOL)d[0]=e;if((e=c.getAsObject().EventID2)&&!d[1]||d[1]===EVENT_CLEAR_SOL)d[1]=
e;(e=c.getAsObject().SmellID)&&e!==SMELL_NONE&&(a.SmellID=e);(e=c.getAsObject().GlasswareID1)&&(p[m]=e);f[0]&&a.AnaID!==f[0]&&(a.AnaID=f[0],a.AnaAdspect=ADSPECT_SOLID);DEBUG&&console.log(LOG_PROMPT,"Reaction ID",c.getAsObject().TestID,"between analyte and reagents without water\n",GetIonFormulaByID(IonID),"+",GetReaLabelByID(a.ReaID[0]),"+",GetReaLabelByID(a.ReaID[1]),"+",GetReaLabelByID(a.ReaID[2]),"->",GetMolFormulaByID(f[0]),"+",GetMolFormulaByID(f[1]),"\nEvents:",GetEventByID(d[0]),",",GetEventByID(d[1]),
"\nSmell:",GetSmellByID(a.SmellID))}c.free()}}else 2===a.ReaNum&&(c=ReactionQuery2R(a),c.step()&&(f[0]=c.getAsObject().ProductID1,f[0]&&(u=ColorByID(c.getAsObject().SolutionColorID),g[0]=c.getAsObject().ColorID1,g[1]=c.getAsObject().ColorID2,b[0]=ColorByID(g[0]),b[1]=ColorByID(g[1]),d[0]=c.getAsObject().EventID1,d[1]=c.getAsObject().EventID2,f[1]=c.getAsObject().ProductID2,h=c.getAsObject().SmellID,p[m]=c.getAsObject().GlasswareID1,h&&h!==SMELL_NONE&&(a.SmellID=h),f[0]&&a.AnaID!=f[0]&&(a.AnaID=f[0],
a.AnaAdspect=ADSPECT_SOLID),DEBUG&&console.log(LOG_PROMPT,"Reaction ID",c.getAsObject().TestID,"between 2 reagents whitout water\n",GetReaLabelByID(a.ReaID[0]),"+",GetReaLabelByID(a.ReaID[1]),"->",GetMolFormulaByID(f[0]),"+",GetMolFormulaByID(f[1]),"\nEvents:",GetEventByID(d[0]),",",GetEventByID(d[1]),"\nSmell:",GetSmellByID(a.SmellID)))),c.free());f[1]===l&&(a.AnaQty/=2,ReaAdd(a,REA_ID_DUMMYINSOL,a.AnaQty,ADSPECT_SOLID))}!a.Water||a.Type===GLASS_TYPE_WATCHGLASS||p[0]!==GLASS_ID_WATCHGLASS&&p[1]!==
GLASS_ID_WATCHGLASS&&p[2]!==GLASS_ID_WATCHGLASS||(d[0]=EVENT_NONE);var r;q=c=p=f=!1;e=0!==a.PaperID;h=!1;!u||u==COLOR_WHITE||a.LiqColor&&a.LiqColor!==COLOR_RED&&"#FFAAAA"!==a.LiqColor&&a.LiqColor!==COLOR_WHITE||(a.LiqColor=u);a.AnaID&&(a.AnaAdspect===ADSPECT_LIQUID?c=!0:q=!0);for(m=0;m<a.ReaNum;++m)switch(a.ReaAdspect[m]){case ADSPECT_LIQUID:c=!0;break;case ADSPECT_PAPER:e=!0;break;case ADSPECT_PLATE:var w=ColorByID(COLOR_ID_METALLICRED);h=!0;break;case ADSPECT_POWDER:case ADSPECT_SOLID:q=!0}a.LiqOpac=
a.LiqDefOpac;for(l=0;2>l;++l)switch(d[l]){case EVENT_BIPHASIC:a.OrgColor=b[l];break;case EVENT_EFFERV:case EVENT_EFFERVSLIGHT:var x=b[l];f=!0;break;case EVENT_FLAME:var y=ColorFlameByID(g[l]);p=!0;break;case EVENT_INDICATORCOL:var z=b[l];break;case EVENT_PLATECOL:w=b[l];break;case EVENT_PRECIPITATE:t=ADSPECT_LIQUID_SUSP;a.SolidColor=b[l];c=!0;l||(a.AnaAdspect=ADSPECT_SOLID,q=!0);break;case EVENT_SUSPENSION:a.LiqColor=b[l],a.LiqOpac=SUSP_OPACITY,q=!1}a.LiqAdspect=q?t:ADSPECT_LIQUID_NONE;if(r=a.Handle.querySelector("#Solid"))r.setAttribute("visible",
q),q&&ColorSet(r,a.SolidColor);if(r=a.Handle.querySelector("#Solid-Paper")){if(e)if(a.Type===GLASS_TYPE_TESTTUBE)switch(a.PaperID){case REA_ID_PAPER:a.AnaID===MOLID_SO2&&a.PaperReaID===REA_ID_K2CR2O7&&ColorPaperSet(a,"#D0FFCB");break;case REA_ID_UNIVIND:a.AnaID===MOLID_NH4OH&&a.PaperWater&&z&&ColorPaperSet(a,ColorFromPh(9))}else a.PaperID===REA_ID_UNIVIND&&(a.PaperWater||a.Water)&&ColorPaperSet(a,ColorFromPh(GetMixPh(a)));r.setAttribute("visible",e)}if(r=a.Handle.querySelector("#Solid-Copper"))h&&
ColorSet(r,w),r.setAttribute("visible",h);LiquidUpdate(a);if(f){if(r=a.Handle.querySelector("#Particle"))x===COLOR_WHITE?r.setAttribute("particle-system","color: white"):r.setAttribute("particle-system","color: "+x),r.setAttribute("particle-system","enabled: true"),DisableShadowAll(),setTimeout(function(){r.setAttribute("particle-system","enabled: false");DisableShadowAll()},EFFERV_DURATION);a.Stirred=!0}p&&(r=a.Handle.querySelector("#Flame"))&&(y!==COLOR_WHITE&&r.setAttribute("particle-system","color: "+
y),a.Burning||(r.setAttribute("particle-system","enabled: true"),a.Burning=!0),DisableShadowAll());DEBUG&&console.log(LOG_PROMPT,"Show:","\nEffervescence:",f,"\nLiquid:",c,"\nSolid:",q,"\nPaper:",e,"\nPlate:",h,"\nColor1:",b[0],"\nColor2:",b[1])}}
function ReactionQueryA1R(a,b,g,d){d||(d=a.ReaID[0]);return a.Water?a.PaperID===REA_ID_UNIVIND&&a.Type===GLASS_TYPE_TESTTUBE&&a.PaperWater?hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE (IonID = "+b+" AND Water AND ReagentID1 = "+d+" AND ReagentID2 = "+REA_ID_UNIVIND+" AND ReagentID3 IS NULL AND HeatTime <= "+a.HeatTime+");"):hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE (IonID = "+
b+" AND (AmbientID IS NULL OR AmbientID = "+g+") AND Water AND ReagentID1 = "+d+" AND ReagentID2 IS NULL AND ReagentID3 IS NULL AND HeatTime <= "+a.HeatTime+");"):hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE (IonID = "+b+" AND NOT Water AND "+(a.Burning?"":"NOT ")+"Fire AND ReagentID1 = "+d+" AND ReagentID2 IS NULL AND ReagentID3 IS NULL AND HeatTime <= "+a.HeatTime+");")}
function ReactionQueryA2R(a,b,g,d,f){d||(d=a.ReaID[0],f=a.ReaID[1]);return a.Water?hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE (IonID = "+b+" AND (AmbientID IS NULL OR AmbientID = "+g+") AND Water AND ((ReagentID1 = "+d+" AND ReagentID2 = "+f+") OR (ReagentID1 = "+f+" AND ReagentID2 = "+d+")) AND ReagentID3 IS NULL AND HeatTime <= "+a.HeatTime+");"):hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE (IonID = "+
b+" AND NOT Water AND "+(a.Burning?"":"NOT ")+"Fire AND ((ReagentID1 = "+d+" AND ReagentID2 = "+f+") OR (ReagentID1 = "+f+" AND ReagentID2 = "+d+")) AND ReagentID3 IS NULL AND HeatTime <= "+a.HeatTime+");")}
function ReactionQueryA3R(a,b,g,d,f){g||(g=a.ReaID[0],d=a.ReaID[1],f=a.ReaID[2]);return a.Water?hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE (IonID = "+b+" AND Water AND ((ReagentID1 = "+g+" AND ReagentID2 = "+d+" AND ReagentID3 = "+f+") OR (ReagentID1 = "+g+" AND ReagentID2 = "+f+" AND ReagentID3 = "+d+") OR (ReagentID1 = "+d+" AND ReagentID2 = "+f+" AND ReagentID3 = "+g+") OR (ReagentID1 = "+d+
" AND ReagentID2 = "+g+" AND ReagentID3 = "+f+") OR (ReagentID1 = "+f+" AND ReagentID2 = "+g+" AND ReagentID3 = "+d+") OR (ReagentID1 = "+f+" AND ReagentID2 = "+d+" AND ReagentID3 = "+g+")) AND HeatTime <= "+a.HeatTime+");"):hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE (IonID = "+b+" AND NOT Water AND "+(a.Burning?"":"NOT ")+"Fire AND ((ReagentID1 = "+g+" AND ReagentID2 = "+d+" AND ReagentID3 = "+
f+") OR (ReagentID1 = "+g+" AND ReagentID2 = "+f+" AND ReagentID3 = "+d+") OR (ReagentID1 = "+d+" AND ReagentID2 = "+f+" AND ReagentID3 = "+g+") OR (ReagentID1 = "+d+" AND ReagentID2 = "+g+" AND ReagentID3 = "+f+") OR (ReagentID1 = "+f+" AND ReagentID2 = "+g+" AND ReagentID3 = "+d+") OR (ReagentID1 = "+f+" AND ReagentID2 = "+d+" AND ReagentID3 = "+g+")) AND HeatTime <= "+a.HeatTime+");")}
function ReactionQueryA3R1E(a,b,g,d){var f=[];for(k=0;k<a.ReaNum;++k)k!==d&&f.push(a.ReaID[k]);return ReactionQueryA2R(a,b,g,f[0],f[1])}
function ReactionQuery2R(a,b,g){b||(b=a.ReaID[0],g=a.ReaID[1]);return a.Water?1===a.ReaNum?hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE (IonID IS NULL AND Water AND ReagentID1 = "+b+" AND ReagentID2 = "+REA_ID_UNIVIND+" AND HeatTime <= "+a.HeatTime+");"):hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE ((IonID IS NULL AND Water AND ReagentID1 = "+b+
" AND ReagentID2 = "+g+") OR (IonID IS NULL AND ReagentID1 = "+g+" AND ReagentID2 = "+b+") AND HeatTime <= "+a.HeatTime+");"):hDb.prepare("SELECT TestID, ProductID1, ProductID2, SolutionColorID, EventID1, ColorID1, EventID2, ColorID2, SmellID, GlasswareID1 FROM Tests WHERE ((IonID IS NULL AND NOT Water AND "+(a.Burning?"":"NOT ")+"Fire AND ReagentID1 = "+b+" AND ReagentID2 = "+g+") OR (IonID IS NULL AND ReagentID1 = "+g+" AND ReagentID2 = "+b+") AND HeatTime <= "+a.HeatTime+");")};
