var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};
$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))return;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<d.length-1;h++){var f=d[h];if(!(f in e))return;e=e[f]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var d=e.value}catch(h){return this.context_.yieldAllIterator_=null,this.context_.throw_(h),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,d){function h(f){f.done?e(f.value):Promise.resolve(f.value).then(b,c).then(h,d)}h(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(d,h){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,e=function(d){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(d||"")+"_"+c++,d)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=$jscomp.global[b[c]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&$jscomp.defineProperty(e.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(f){return f instanceof d?f:new d(function(g,k){g(f)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(f){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(f)};
var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(f){e(f,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var f=this.batch_;this.batch_=[];for(var g=0;g<f.length;++g){var k=f[g];f[g]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(f){this.asyncExecuteFunction(function(){throw f;})};var d=function(f){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var g=this.createResolveAndReject_();
try{f(g.resolve,g.reject)}catch(k){g.reject(k)}};d.prototype.createResolveAndReject_=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.resolveTo_),reject:f(this.reject_)}};d.prototype.resolveTo_=function(f){if(f===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof d)this.settleSameAsPromise_(f);else{a:switch(typeof f){case "object":var g=null!=f;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(f):
this.fulfill_(f)}};d.prototype.resolveToNonPromiseObj_=function(f){var g=void 0;try{g=f.then}catch(k){this.reject_(k);return}"function"==typeof g?this.settleSameAsThenable_(g,f):this.fulfill_(f)};d.prototype.reject_=function(f){this.settle_(2,f)};d.prototype.fulfill_=function(f){this.settle_(1,f)};d.prototype.settle_=function(f,g){if(0!=this.state_)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.state_);this.state_=f;this.result_=g;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};d.prototype.scheduleUnhandledRejectionCheck_=function(){var f=this;e(function(){if(f.notifyUnhandledRejection_()){var g=$jscomp.global.console;"undefined"!==typeof g&&g.error(f.result_)}},1)};d.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var f=$jscomp.global.CustomEvent,g=$jscomp.global.Event,k=$jscomp.global.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):
"function"===typeof g?f=new g("unhandledrejection",{cancelable:!0}):(f=$jscomp.global.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.result_;return k(f)};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var f=0;f<this.onSettledCallbacks_.length;++f)h.asyncExecute(this.onSettledCallbacks_[f]);this.onSettledCallbacks_=null}};var h=new b;d.prototype.settleSameAsPromise_=function(f){var g=this.createResolveAndReject_();
f.callWhenSettled_(g.resolve,g.reject)};d.prototype.settleSameAsThenable_=function(f,g){var k=this.createResolveAndReject_();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};d.prototype.then=function(f,g){function k(n,p){return"function"==typeof n?function(r){try{l(n(r))}catch(t){m(t)}}:p}var l,m,q=new d(function(n,p){l=n;m=p});this.callWhenSettled_(k(f,l),k(g,m));return q};d.prototype.catch=function(f){return this.then(void 0,f)};d.prototype.callWhenSettled_=function(f,g){function k(){switch(l.state_){case 1:f(l.result_);
break;case 2:g(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?h.asyncExecute(k):this.onSettledCallbacks_.push(k);this.isRejectionHandled_=!0};d.resolve=c;d.reject=function(f){return new d(function(g,k){k(f)})};d.race=function(f){return new d(function(g,k){for(var l=$jscomp.makeIterator(f),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(g,k)})};d.all=function(f){var g=$jscomp.makeIterator(f),k=g.next();return k.done?c([]):new d(function(l,
m){function q(r){return function(t){n[r]=t;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(k.value).callWhenSettled_(q(n.length-1),m),k=g.next();while(!k.done)})};return d},"es6","es3");$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(b){var c=$jscomp.checkStringArgs(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var e="";b;)if(b&1&&(e+=c),b>>>=1)c+=c;return e}},"es6","es3");$jscomp.stringPadding=function(a,b){a=void 0!==a?String(a):" ";return 0<b&&a?a.repeat(Math.ceil(b/a.length)).substring(0,b):""};
$jscomp.polyfill("String.prototype.padStart",function(a){return a?a:function(b,c){var e=$jscomp.checkStringArgs(this,null,"padStart");return $jscomp.stringPadding(c,b-e.length)+e}},"es8","es3");$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(b,c){var e=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var d=e.length,h=b.length;c=Math.max(0,Math.min(c|0,e.length));for(var f=0;f<h&&c<d;)if(e[c++]!=b[f++])return!1;return f>=h}},"es6","es3");var WatchDouble=0;
function Boil(a,b){if(ParticleHandle=a.Handle.querySelector("#BoilWater"))b?(ParticleHandle.setAttribute("particle-system","enabled: true"),PlaySound("SND_BoilWater")):(ParticleHandle.setAttribute("particle-system","enabled: false"),StopSound("SND_BoilWater")),DisableShadowAll(),a.Boiling=b}function BoilDelay(a,b,c){!a||!a.Water||a.Boiling&&b||!a.Boiling&&!b||setTimeout(function(){Boil(a,b)},c?c:b?BOIL_DELAY_START:BOIL_DELAY_STOP)}
function ColorBlend(a,b,c){a||(a=COLOR_WHITE);b||(b=COLOR_WHITE);c||(c=.5);var e=$jscomp.makeIterator(a.match(/\w\w/g).map(function(g){return parseInt(g,16)})),d=e.next().value;a=e.next().value;e=e.next().value;var h=$jscomp.makeIterator(b.match(/\w\w/g).map(function(g){return parseInt(g,16)})),f=h.next().value;b=h.next().value;h=h.next().value;d=Math.round(d+(f-d)*c).toString(16).padStart(2,"0");a=Math.round(a+(b-a)*c).toString(16).padStart(2,"0");c=Math.round(e+(h-e)*c).toString(16).padStart(2,
"0");return("#"+d+a+c).toUpperCase()}function ColorByID(a){if(!a)return COLOR_WHITE;var b=COLOR_WHITE;a=hDb.prepare("SELECT HtmlCode FROM Colors WHERE (ColorID = "+a+");");a.step()&&(b=a.getAsObject().HtmlCode);a.free();return b}function ColorByMolID(a){var b=COLOR_WHITE;a=hDb.prepare("SELECT Colors.HtmlCode FROM (Molecules INNER JOIN Colors ON Molecules.ColorID = Colors.ColorID) WHERE (Molecules.MoleculeID = "+a+");");a.step()&&(b=a.getAsObject().HtmlCode);a.free();return b}
function ColorFlameByID(a){a||(a=COLOR_ID_COLORLESS);var b;do{var c=hDb.prepare("SELECT HtmlFlame FROM Colors WHERE (ColorID = "+a+");");c.step()?b=c.getAsObject().HtmlFlame:a=COLOR_ID_COLORLESS;c.free()}while(!b);return b}
function ColorFlameByMolID(a){var b=FLAME_DEF_COLOR,c=hDb.prepare("SELECT Colors.HtmlFlame FROM (Molecules INNER JOIN Ions ON Molecules.CationID1 = Ions.IonID) INNER JOIN Colors ON Ions.FlameTestColorID = Colors.ColorID WHERE (Molecules.MoleculeID="+a+");");c.step()&&(b=c.getAsObject().HtmlFlame,b===FLAME_DEF_COLOR&&(c.free(),c=hDb.prepare("SELECT Colors.HtmlFlame FROM (Molecules INNER JOIN Ions ON Molecules.AnionID = Ions.IonID) INNER JOIN Colors ON Ions.FlameTestColorID = Colors.ColorID WHERE (Molecules.MoleculeID="+
a+");"),c.step()&&(b=c.getAsObject().HtmlFlame)));c.free();return b}function ColorFromPh(a){return 4>a?"#FF0000":6>a?"#FF9933":6.5>a?"#FFFF00":7.5>a?"#00CC66":9>a?"#00FFFF":"#0000FF"}function ColorPaperSet(a,b){var c=a.Handle.querySelector("#Solid-Paper");c&&(ColorSet(c,b),c.setAttribute("event-set__leave","_event: mouseleave; _subtarget: .paper-event; material.color: "+b),a.PaperColor=b)}
function ColorSet(a,b){if(a)if(b||(b=COLOR_WHITE),Primitive=a.querySelectorAll("*"),Primitive.length)for(a=0;a<Primitive.length;a++)Primitive[a].setAttribute("color",b);else a.setAttribute("color",b)}function ColorTone(a,b){return"#"+a.replace(/^#/,"").replace(/../g,function(c){return("0"+Math.min(255,Math.max(0,parseInt(c,16)+b)).toString(16)).substr(-2)})}
function CookieRead(a){if(0<document.cookie.length){var b=document.cookie.indexOf(a+"=");if(-1!=b)return b=b+a.length+1,a=document.cookie.indexOf(";",b),-1==a&&(a=document.cookie.length),unescape(document.cookie.substring(b,a))}return""}function CookieWrite(a,b,c){var e=new Date;e.setTime((new Date).getTime()+864E5*b);document.cookie=a+"="+escape(c)+"; expires="+e.toGMTString()+"; path=/"}
function DetectDevice(){if(AFRAME.utils.device.isMobileVR())return DEVICE_TYPE_MOBILE|DEVICE_TYPE_VR;var a=AFRAME.utils.device.isMobile()?DEVICE_TYPE_MOBILE:DEVICE_TYPE_DESKTOP;AFRAME.utils.device.checkHeadsetConnected()&&(a|=DEVICE_TYPE_VR);return a}function DisableShadow(a,b,c){a.setAttribute("shadow","cast: true; receive: true");b||(b="false");c||(c="false");a.setAttribute("shadow","cast: "+b+"; receive: "+c)}
function DisableShadowAll(){DisableShadow(Dropper.Handle);DisableShadow(Nichrome.Handle);DisableShadow(Scene.querySelector("#PosCentrifuge"));DisableShadow(Scene.querySelector("#PosTv"));DisableShadow(Scene.querySelector("#PosWork"));DisableShadow(Spatula);DisableShadow(Stirrer.Handle);DisableShadow(Tv.Controls);DisableShadow(Tv.Handle.querySelector("#TvFrame"));DisableShadow(Scene.querySelector("#UmbrellaStand"),"true","false");DisableShadow(WatchGlass.Handle);DisableShadow(Workbench.querySelector("#BookLabel"))}
function DoubleClick(a,b){WatchDouble+=1;setTimeout(function(){2===WatchDouble?b&&b():1===WatchDouble&&a&&a();WatchDouble=0},DBLCLICK_DELAY)}function EnableSound(a){for(var b=Scene.querySelectorAll("[sound]"),c=0;c<b.length;++c)b[c].setAttribute("sound","volume: "+(a?"1":"0"));Prefs.SoundActive=a}
function FillAnalytes(){var a=document.querySelector("#DlgMenuAna"),b=MENUANA_OFFSET_X,c=MENUANA_OFFSET_BEGIN_Y;CreateGuiButton(a,"BT_AnaCode",Msg.DlgMenuAnaCode,"#990000","#cc0000",MENUANA_OFFSET_BEGIN_X,c);CreateGuiButton(a,"BT_AnaRndAll",Msg.DlgMenuAnaRndAll,"#009900","#00cc00",b,c);CreateGuiButton(a,"BT_AnaRndSol",Msg.DlgMenuAnaRndSol,"#002966","#003d99",b,c);CreateGuiButton(a,"BT_AnaRndInsol",Msg.DlgMenuAnaRndInsol,"#664d00","#cc9900",b,c);var e=4,d=1;hDb.each("SELECT MoleculeID, Formula, SolWater FROM Molecules WHERE (Analyte) ORDER BY SolWater, Formula;",
function(h){e%MENUANA_ITEMDBYLINE?b=MENUANA_OFFSET_X:(b=MENUANA_OFFSET_BEGIN_X,c+=MENUANA_STEP_Y,++d);if(h.SolWater){var f="#002966";var g="#003d99"}else f="#664d00",g="#cc9900";CreateGuiButton(a,"BT_Ana"+h.MoleculeID,SubNums(h.Formula),f,g,b,c);++NumAnalytes;++e});a.setAttribute("height",MENUANA_HEIGHT+d*(MENUANA_BUTTON_HEIGHT+.05))}
function FillReagents(){var a=0,b=1.41,c={},e=Asset.querySelector("#CanvasReaLiquid"),d=Asset.querySelector("#CanvasReaSolid"),h=document.querySelector("#ReaLiquid"),f=document.querySelector("#ReaSolid");hDb.each("SELECT Reagents.ReagentID, Reagents."+Msg.SqlReagent+", Reagents."+Msg.SqlReagentNameSc+", Reagents.PhysicalStateID, Reagents.PhysicalAdspectID, Reagents.Water, Reagents.WaterMisc, Colors.HtmlCode FROM Reagents INNER JOIN Colors ON Reagents.ColorID = Colors.ColorID ORDER BY Reagents.PhysicalStateID, Reagents.Reagent;",
function(g){var k=g.ReagentID;if(2==g.PhysicalStateID){var l=e.cloneNode(!0);var m=h.cloneNode(!0);var q=REALIQ_LBL_OFFSET_Y}else l=d.cloneNode(!0),m=f.cloneNode(!0),q=REASOL_LBL_OFFSET_Y;l.setAttribute("id","CanvasReaLbl_"+k);Asset.appendChild(l);var n=l.getContext("2d");n.fillStyle="white";n.fillRect(0,0,l.width,l.height);n.fillStyle="#000";n.font="48px sans-serif";n.textAlign="center";n.fillText(SubNums(g[Msg.SqlReagent]),256,q);l=-.85+.12*a+" "+b+" -0.7";m.querySelector("#Label").setAttribute("src",
"#CanvasReaLbl_"+k);m.setAttribute("id","Reagent_"+k);m.setAttribute("Position",l);m.setAttribute("Visible","true");g.PhysicalAdspectID===ADSPECT_PAPER?m.querySelector("#Solid").setAttribute("src","#TexPaperStripes"):g.PhysicalAdspectID===ADSPECT_PLATE&&m.querySelector("#Solid").setAttribute("src","#TexCopper");ScReaNames=g[Msg.SqlReagentNameSc].split(";");for(l=0;l<ScReaNames.length;++l)c[Msg.ScTake+" "+ScReaNames[l].trim()]=function(){ScReagentClick("Reagent_"+k)};m.setAttribute("ReaId",k);m.setAttribute("ReaPhysicalState",
2==g.PhysicalStateID?"liquid":"solid");m.setAttribute("ReaPhysicalAdspect",g.PhysicalAdspectID);m.setAttribute("ReaWater",0>g.Water);m.setAttribute("ReaWaterMisc",0>g.WaterMisc);g.HtmlCode&&m.querySelector(2==g.PhysicalStateID?"#Liquid":"#Solid").setAttribute("color",g.HtmlCode);Workbench.prepend(m);++a;14<a&&(a=0,b+=.3)});Canvas=d.cloneNode(!0);AnalyteHandle=f.cloneNode(!0);Canvas.setAttribute("id","CanvasAnaLbl");Asset.appendChild(Canvas);TexPrint(Canvas,Msg.Analyte,REASOL_LBL_OFFSET_Y);AnalyteHandle.querySelector("#Label").setAttribute("src",
"#CanvasAnaLbl");AnalyteHandle.setAttribute("id","Analyte");AnalyteHandle.setAttribute("Position",ANA_POSITION);AnalyteHandle.setAttribute("Visible","true");AnalyteHandle.setAttribute("ReaPhysicalState","solid");AnalyteHandle.setAttribute("ReaPhysicalAdspect","1");c[Msg.ScTake+" "+Msg.ScAnalyte]=function(){ScReagentClick("Analyte")};Workbench.prepend(AnalyteHandle);TexPrint("CanvasWashBottle",Msg.WaterDist);TexPrint("CanvasTrash",Msg.Trash,84,64,!0);Prefs.SpeechRecAvail&&annyang.addCommands(c)}
function GetMolFormulaByID(a){if(!a)return null;a=hDb.prepare("SELECT Formula FROM Molecules WHERE (MoleculeID="+a+");");if(a.step())var b=a.getAsObject().Formula;a.free();return b}
function GlassEmpty(a,b){var c,e=a.Handle;b||(b=EMPTY_ALL);if(b&EMPTY_LIQUID){var d=e.querySelectorAll('[id^="Liquid"]');for(c=0;c<d.length;c++)d[c].setAttribute("visible",!1)}if(b&EMPTY_SOLID||b&EMPTY_PAPER||b&EMPTY_PLATE){d=e.querySelectorAll('[id^="Solid"]');if(b&EMPTY_PAPER){for(c=0;c<d.length;c++)"Solid-Paper"==d[c].id&&d[c].setAttribute("visible",!1);a.PaperColor=null;a.PaperID=0;a.PaperReaID=0;a.PaperWater=!1}if(b&EMPTY_PLATE){for(c=0;c<d.length;c++)"Solid-Copper"==d[c].id&&d[c].setAttribute("visible",
!1);for(c=0;c<a.ReaNum;++c)a.ReaAdspect[c]===ADSPECT_PLATE&&(ReaRemove(a,c),--c)}if(b&EMPTY_SOLID)for(c=0;c<d.length;c++)"Solid-Paper"!=d[c].id&&"Solid-Copper"!=d[c].id&&d[c].setAttribute("visible",!1)}(b&EMPTY_LIQUID||b&EMPTY_SOLID)&&a.Type===GLASS_TYPE_TESTTUBE&&e.querySelector("#Suspension").setAttribute("visible",!1);a===Stirrer||GlassWater(a)?(a.Clean=!0,a.SmellID=SMELL_NONE):a.Clean=!1;if(b===EMPTY_ALL)a.AnaAdspect=ADSPECT_SOLID,a.AnaID=0,a.AnaQty=0,a.Boiling=!1,a.Burning=!1,a.CentTime=0,a.HeatTime=
0,a.LiqAdspect=ADSPECT_LIQUID_NONE,a.LiqColor=null,a.LiqLvl=0,a.LiqOpac=a.LiqDefOpac,a.OrgColor=null,a.ReaAdspect=[],a.ReaID=[],a.ReaNum=0,a.ReaQty=[],a.SolidColor=null,a.Stirred=!0,a.Water=!1,DEBUG&&(a.SmellID=SMELL_NONE);else{if(b&EMPTY_LIQUID){a.AnaAdspect===ADSPECT_LIQUID&&(a.AnaAdspect=ADSPECT_SOLID,a.AnaQty=0,b&EMPTY_SUBST&&(a.AnaID=0));for(c=0;c<a.ReaNum;++c)a.ReaAdspect[c]===ADSPECT_LIQUID&&(b&EMPTY_SUBST?(ReaRemove(a,c),--c):a.ReaQty[c]=0);a.Boiling=!1;a.Burning=!1;a.CentTime=0;a.HeatTime=
0;a.LiqAdspect=ADSPECT_LIQUID_NONE;a.LiqColor=null;a.LiqLvl=0;a.LiqOpac=a.LiqDefOpac;a.OrgColor=null;a.Water=!1}if(b&EMPTY_SOLID){a.AnaAdspect===ADSPECT_SOLID&&(a.AnaQty=0,b&EMPTY_SUBST&&(a.AnaID=0));for(c=0;c<a.ReaNum;++c)a.ReaAdspect[c]===ADSPECT_SOLID&&(b&EMPTY_SUBST?(ReaRemove(a,c),--c):a.ReaQty[c]=0);a.SolidColor=null}}}function GlassGetByHandle(a){for(var b=0;b<GlassWare.length;b++)if(GlassWare[b].Handle==a)return GlassWare[b];return null}
function GlassIsClean(a){if(DEBUG_GLASS_CLEAN)return!0;switch(a.Type){case GLASS_TYPE_DROPPER:if(!a.Clean&&!a.ReaNum&&!a.AnaID)return CleanDropperFirst?(ShowError(Msg.SsCleanGlassware1+". "+Msg.SsDropperClean),CleanDropperFirst=!1):ShowError(Msg.SsCleanGlassware1),!1;break;case GLASS_TYPE_STIRRER:if(!a.Clean)return ShowError(Msg.SsStirrerClean),!1;break;default:if(!a.Clean&&!a.ReaNum&&!a.AnaID)return CleanGlassFirst?(ShowError(Msg.SsCleanGlassware1+". "+Msg.SsCleanGlassware2),CleanGlassFirst=!1):
ShowError(Msg.SsCleanGlassware1),!1}return!0}function GlassIsEmpty(a){if(a.Type===GLASS_TYPE_DROPPER){if(a.AnaID&&a.AnaQty)return!1;if(a.ReaNum)for(var b=$jscomp.makeIterator(a.ReaQty),c=b.next();!c.done;c=b.next())if(c.value)return!1;return!a.Water}return!a.AnaID&&!a.Water&&!a.ReaNum&&!a.PaperID}
function GlassPrecipitate(a){if(a.AnaID&&(a.AnaAdspect===ADSPECT_SOLID||a.AnaAdspect===ADSPECT_POWDER))return!0;if(!a.ReaNum)return!1;a=$jscomp.makeIterator(a.ReaAdspect);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b===ADSPECT_SOLID||b===ADSPECT_POWDER)return!0;return!1}function GlassSameSubst(a,b){if(a===b)return!0;if(a.ReaNum!==b.ReaNum)return!1;for(var c=$jscomp.makeIterator(a.ReaID),e=c.next();!e.done;e=c.next())if(-1===b.ReaID.indexOf(e.value))return!1;return a.AnaID===b.AnaID}
function GlassWater(a){if(a.Type===GLASS_TYPE_DROPPER){if(a.AnaID&&a.AnaQty)return!1;if(a.ReaNum)for(var b=$jscomp.makeIterator(a.ReaQty),c=b.next();!c.done;c=b.next())if(c.value)return!1;return a.Water}return a.Water&&!a.AnaID&&!a.ReaNum}
function GotoFootprint(a){Camera.getAttribute("rotation");var b=Floor.querySelector("#"+a),c=b.getAttribute("position");b=b.getAttribute("rotation");var e=Camera.components["look-controls"].pitchObject.rotation.x,d=NormalizeAngleRad(Camera.components["look-controls"].yawObject.rotation.y),h=NormalizeAngleRad(b.z*MATH_DEG2RAD),f=40,g=e/f,k=(h-d)/f;a="PosCentrifuge"==a?-.5:0;c=new THREE.Vector3(c.x,c.y,c.z);Floor.object3D.localToWorld(c);Scene.object3D.worldToLocal(c);Camera.removeAttribute("animation");
CameraRig.removeAttribute("animation");Camera.setAttribute("animation","dur: 1000; property: position; to: 0 "+a+" 0; easing: easeInOutCubic;");CameraRig.setAttribute("animation","dur: 1000; property: position; to: "+c.x+" "+CameraRigOffsetY+" "+c.z+"; easing:easeInOutCubic;");var l=setInterval(function(){--f?(e-=g,d+=k,Camera.components["look-controls"].pitchObject.rotation.x=e,Camera.components["look-controls"].yawObject.rotation.y=d):(Camera.components["look-controls"].pitchObject.rotation.x=0,
Camera.components["look-controls"].yawObject.rotation.y=h,clearInterval(l))},10)}
function HeatingThread(){var a,b,c,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){1==d.nextAddress&&(a=null,b=[null,null,null,null]);if(6!=d.nextAddress)return Heater.WhatGlass?d.yield(Sleep(1E3),6):d.jumpTo(2);if(a!=Heater.WhatGlass){BoilDelay(a,!1);BoilDelay(Heater.WhatGlass,!0);for(c=0;c<WaterBath.DockHole.length;++c)b[c]=null;a=Heater.WhatGlass}else++Heater.WhatGlass.HeatTime,Heater.WhatGlass!==WaterBath&&Reaction(Heater.WhatGlass);if(Heater.WhatGlass===WaterBath)for(c=0;c<WaterBath.DockHole.length;++c)(e=
WaterBath.DockHole[c])&&e==b[c]&&(++e.HeatTime,Reaction(e)),b[c]=e;return d.jumpTo(2)})}function LeftMbPressed(a){return"which"in a?1===a.which:"button"in a?0===a.button:!1}
function LiquidMove(a,b,c){if(b.LiqLvl){"undefined"===typeof c&&(c=1);a.LiqLvl+=c;a.LiqLvl>a.LiqLvlMax&&(a.LiqLvl=a.LiqLvlMax);a.LiqColor=a.ReaNum?ColorBlend(a.LiqColor,b.LiqColor,1/a.LiqLvl):b.LiqColor;a.Water=!0;LiquidUpdate(a);GlassIsEmpty(a)?a.Stirred=b.Stirred:a.Stirred=GlassWater(a)&&GlassWater(a);if(b!==WashBottle){var e=EMPTY_ALL;b.PaperID&&(a.Type===GLASS_TYPE_DROPPER||a.Type===GLASS_TYPE_TESTTUBE?e&=~EMPTY_PAPER:(a.PaperColor=b.PaperColor,a.PaperID=b.PaperID,a.PaperReaID=b.PaperReaID,a.PaperWater=
b.PaperWater,b.PaperColor=null,b.PaperID=0,b.PaperReaID=0,b.PaperWater=!1));for(var d=0;d<b.ReaNum;d++)if(b.ReaAdspect[d]===ADSPECT_PLATE&&a.Type===GLASS_TYPE_DROPPER)e&=~EMPTY_PLATE;else if(a.Type!==GLASS_TYPE_DROPPER||b.ReaAdspect[d]!==ADSPECT_SOLID&&b.ReaAdspect[d]!==ADSPECT_POWDER||b.LiqAdspect===ADSPECT_LIQUID_SUSP){var h=a.ReaID.indexOf(b.ReaID[d]),f=b.ReaQty[d]*c/b.LiqLvl;b.ReaQty[d]-=f;-1===h?(a.ReaAdspect.push(b.ReaAdspect[d]),a.ReaID.push(b.ReaID[d]),a.ReaQty.push(f),++a.ReaNum):a.ReaQty[h]+=
f;b.ReaAdspect[d]===ADSPECT_PLATE&&(ReaRemove(b,d),--d)}else a.SolidColor=b.SolidColor;b.AnaID&&(a.Type!==GLASS_TYPE_DROPPER||a.Type===GLASS_TYPE_DROPPER&&b.LiqLvl<=c||b.AnaAdspect!==ADSPECT_SOLID&&b.AnaAdspect!==ADSPECT_POWDER||b.LiqAdspect===ADSPECT_LIQUID_SUSP)&&(!a.AnaID&&b.AnaQty&&(a.AnaID=b.AnaID,a.AnaAdspect=b.AnaAdspect,a.SolidColor=b.SolidColor),f=b.AnaQty*c/b.LiqLvl,a.AnaQty+=f,b.AnaQty-=f);a.Clean=!1;b.LiqLvl-=c;0>=b.LiqLvl?(b.Type===GLASS_TYPE_DROPPER&&(e&=~EMPTY_SUBST),GlassEmpty(b,e)):
LiquidUpdate(b)}Reaction(a)}}
function LiquidUpdate(a){for(var b=a.Handle.querySelectorAll('[id^="Liquid"]'),c=0;c<b.length;c++)b[c].setAttribute("visible",!1);if(GlassLiquid(a)&&(b=a.Handle.querySelector("#Liquid-"+10*a.LiqLvl))){c=b.querySelector("a-cylinder");var e=b.querySelector("a-sphere");a.LiqAdspect===ADSPECT_LIQUID_SUSP?(c&&(c.setAttribute("material","opacity",1),c.setAttribute("material","src: #TexSuspGrad"),c.setAttribute("material","transparent: true")),e&&(e.setAttribute("material","opacity",1),e.setAttribute("material",
" src: #TexSuspSol")),a.LiqColor===COLOR_WHITE?ColorSet(b,a.SolidColor):ColorSet(b,ColorBlend(a.LiqColor,a.SolidColor,.5))):(c&&(c.setAttribute("material","src:"),c.setAttribute("material","opacity",a.LiqOpac),c.setAttribute("material","transparent: false")),e&&(e.setAttribute("material","src:"),e.setAttribute("material","opacity",a.LiqOpac)),ColorSet(b,a.LiqColor));b.setAttribute("visible",!0)}a.Type===GLASS_TYPE_TESTTUBE&&(-1!==a.ReaID.indexOf(REA_ID_CH2CL2)?(b=a.Handle.querySelector("#Liquid-Dual"),
ColorSet(b,a.Stirred&&a.OrgColor?a.OrgColor:COLOR_WHITE),b.setAttribute("visible",!0)):RingTestCheck(a)&&!a.Stirred&&-1!==a.ReaID.indexOf(REA_ID_H2SO4_CONC)&&(b=a.Handle.querySelector("#Liquid-Dual"),ColorSet(b,COLOR_WHITE),b.setAttribute("visible",!0),a.AnaID===MOLID_FENOSO4&&a.Handle.querySelector("#Liquid-Ring").setAttribute("visible",!0)))}
function LoadBinaryFile(a,b){var c=new XMLHttpRequest;c.open("GET",a,!0);c.responseType="arraybuffer";c.onload=function(){for(var e=new Uint8Array(c.response),d=[],h=0;h!=e.length;++h)d[h]=String.fromCharCode(e[h]);b(d.join(""))};c.send()}
function MoveToTarget(a,b,c){var e=500,d=GlassReady.Handle,h=d.getAttribute("position"),f=GlassGetByHandle(a);a=PositionToLocal(Workbench,a);GlassReady.StartPosX=h.x;GlassReady.StartPosY=h.y;GlassReady.StartPosZ=h.z;if(f){if(f.Type!=GLASS_TYPE_TESTTUBE){var g=f.Handle.getAttribute("position");f=f.PosY-g.y}else g=f.Handle.getAttribute("position"),f=new THREE.Vector3(0,f.PosY,0),g=new THREE.Vector3(0,g.y,0),Rack.object3D.updateMatrixWorld(),Rack.object3D.localToWorld(f),Rack.object3D.localToWorld(g),
WorkBench.object3D.worldToLocal(f),WorkBench.object3D.worldToLocal(g),f=f.y-g.y;b-=f;c+=f}d.removeAttribute("animation__M1");d.removeAttribute("animation__M2");d.setAttribute("animation__M1","dur: 500; property: position ; from: "+h.x+" "+h.y+" "+h.z+"; to: "+a.x+" "+(h.y+b)+" "+a.z);d.setAttribute("animation__M2","dur: 500; property: rotation; from: 90 0 0; to: 0 0 0");c?(GlassReady.MoveDown=b+c,d.removeAttribute("animation__M3"),d.setAttribute("animation__M3","delay: 500; dur: 500; property: position ; from: "+
a.x+" "+(h.y+b)+" "+a.z+"; to: "+a.x+" "+(h.y-c)+" "+a.z),e+=500):GlassReady.MoveDown=0;return e}function NicromeError(a){FlameTestFirst?(ShowError(a+". "+Msg.SsFlameTest),FlameTestFirst=!1):ShowError(a)}function NormalizeAngleRad(a){a-=Math.floor(a/MATH_2PI)*MATH_2PI;a>Math.PI&&(a-=MATH_2PI);return a}
function PlayDrainSound(a,b){b||(b=GlassReady.Obj);PlaySound(a.querySelector(b.Type===GLASS_TYPE_TESTTUBE?RingTest?"#SND_LiquidDroplet4":b.PaperID?"#SND_LiquidDroplet":"#SND_LiquidDrain1":"#SND_LiquidDrain2"))}function PlaySound(a){Prefs.SoundActive&&("string"==typeof a&&(a=Scene.querySelector("#"+a)),a.components.sound.playSound())}function PositionToLocal(a,b){var c=new THREE.Vector3;a.object3D.updateMatrixWorld();b.object3D.getWorldPosition(c);a.object3D.worldToLocal(c);return c}
function ReaAdd(a,b,c,e){var d=a.ReaNum?a.ReaID.indexOf(b):-1;if(-1===d)return a.ReaAdspect.push(e),a.ReaID.push(b),a.ReaQty.push(c),++a.ReaNum,!0;a.ReaAdspect[d]=e;a.ReaQty[d]+=c;return!1}function ReaId2AnaId(a){var b=0;a=hDb.prepare("SELECT Reagents.MoleculeID1, Reagents.MoleculeID2, Reagents.MoleculeID3 FROM Reagents WHERE (Reagents.ReagentID="+a+");");a.step()&&(b=a.getAsObject().MoleculeID1);a.free();return b}
function ReaId2SmellId(a){var b=SMELL_NONE;a=hDb.prepare("SELECT SmellID FROM Reagents WHERE (ReagentID="+a+");");a.step()&&(b=a.getAsObject().SmellID);a.free();return b}function ReaRemove(a,b){!a.ReaNum||b>a.ReaNum||(a.ReaID.splice(b,1),a.ReaAdspect.splice(b,1),a.ReaQty.splice(b,1),--a.ReaNum)}
function RaycastableObj(a,b){var c=Cursor.getAttribute("raycaster"),e=c.objects;a=", "+a;-1==e.search(a)?b&&(e+=a):b||(e=e.replace(a,""));c.objects=e;CameraRig.querySelector("#HandLeft").getAttribute("raycaster").objects=e;CameraRig.querySelector("#HandRight").getAttribute("raycaster").objects=e}
function ReturnFromTarget(a,b){var c=GlassReady.Handle,e=c.getAttribute("position");b=b?"animation__L":"animation__M3";GlassReady.MoveDown&&(c.removeAttribute("animation__M1"),c.setAttribute("animation__M1","delay: "+a+"; dur: 500; property: position ; from: "+e.x+" "+e.y+" "+e.z+"; to: "+e.x+" "+(e.y+GlassReady.MoveDown)+" "+e.z),a+=500);c.removeAttribute("animation__M2");c.removeAttribute(b);c.setAttribute("animation__M2","delay: "+a+"; dur: 500; property: position ; from: "+e.x+" "+(e.y+GlassReady.MoveDown)+
" "+e.z+"; to: "+GlassReady.StartPosX+" "+GlassReady.StartPosY+" "+GlassReady.StartPosZ);c.setAttribute(b,"delay: "+a+"; dur: 500; property: rotation; from: 0 0 0; to: 90 0 0")}function RightMbPressed(a){return"which"in a?3==a.which:"button"in a?2==a.button:!1}function RingTestCheck(a){return a.Type===GLASS_TYPE_TESTTUBE&&a.Water?-1!==a.ReaID.indexOf(REA_ID_FESO4):!1}
function Sec2Time(a){if(!a)return"00:00";var b=parseFloat(a).toFixed(3);a=Math.floor(b/60)%60;b=Math.floor(b-60*a);return("000"+a).slice(-2)+":"+("000"+b).slice(-2)}
function SetCheckToggle(a,b,c){a=a.querySelector(b);b=a.components["gui-toggle"];var e=a.components["gui-item"],d=a.querySelector("a-box"),h=d.querySelector("a-box"),f=e.data.height/5,g=.5*-e.data.height+2*f;e=.5*e.data.height-2*f;a.setAttribute("checked",c);c?(d.removeAttribute("animation__colorOut"),h.removeAttribute("animation__positionOut"),d.setAttribute("animation__colorIn","property: material.color; from: "+b.data.borderColor+"; to:"+b.data.activeColor+"; dur:200; easing:easeInOutCubic;"),
h.setAttribute("animation__positionIn","property: position; from: "+g+" 0 0.02; to:"+e+" 0 0.02; dur:200; easing:easeInOutCubic;")):(d.removeAttribute("animation__colorIn"),h.removeAttribute("animation__positionIn"),d.setAttribute("animation__colorOut","property: material.color; from: "+b.data.activeColor+"; to:"+b.data.borderColor+"; dur:200; easing:easeInOutCubic;"),h.setAttribute("animation__positionOut","property: position; from: "+e+" 0 0.02; to:"+g+" 0 0.02; dur:200; easing:easeInOutCubic;"))}
function SetDetail(a){a?Shadow.setAttribute("shadow","cast: true; receive: true"):Shadow.setAttribute("shadow","cast: false; receive: false");DisableShadowAll();for(var b=Scene.querySelectorAll(".hidetailobj"),c=0;c<b.length;c++)b[c].setAttribute("visible",a);SetSegments(a?AFRAME_DETAIL_HI:AFRAME_DETAIL_LOW)}
function SetSegments(a){var b,c=a/2,e=a/4;var d=Scene.querySelectorAll("a-circle");for(b=0;b<d.length;b++)d[b].setAttribute("geometry","segments: "+a);d=Scene.querySelectorAll("a-cone, a-cylinder");for(b=0;b<d.length;b++)d[b].getAttribute("csg-meshs")||d[b].setAttribute("geometry","segmentsRadial: "+a+"; segmentsHeight: "+c);d=Scene.querySelectorAll("a-ring");for(b=0;b<d.length;b++)d[b].setAttribute("geometry","segmentsTheta: "+a+"; segmentsPhi:"+e);d=Scene.querySelectorAll("a-sphere");for(b=0;b<
d.length;b++)d[b].setAttribute("geometry","segmentsHeight:"+a+"; segmentsWidth:"+c)}function SetTextSplash(a){var b=document.getElementById("TextSplash");b.innerHTML="";b.innerHTML="<p>"+a+"</p>"}function LogPrint(a){a=a.split("\n");for(var b=0;b<a.length;++b)AFRAME.log(a[b])}function SaveAs(a,b,c){var e=document.createElement("a");a=new Blob([a],{type:c});e.href=URL.createObjectURL(a);e.download=b;e.click();URL.revokeObjectURL(e.href)}function ShowError(a,b){LogPrint(a);Speak(a,b)}
function ShuffleArray(a){for(var b=a.length-1;0<b;b--){var c=Math.floor(Math.random()*(b+1)),e=a[b];a[b]=a[c];a[c]=e}}function Sleep(a){return new Promise(function(b){a=a||2E3;setTimeout(function(){b()},a)})}
function Speak(a,b){if(a)switch(VoiceType){case VOICE_TYPE_NATIVE:if(Voice.speaking)break;if(!Prefs.VoiceAvail||!Prefs.VoiceActive){b&&b();break}if("it"==Lang){if(!VoiceHandle)break;VoiceHandle.name.startsWith("Google")?(a=a.replace(/becher/gi,"becker"),a=a.replace(/bunsen/gi,"buunsen")):VoiceHandle.name.startsWith("Microsoft")&&-1==VoiceHandle.name.indexOf("Natural")&&(a=a.replace(/bagnomaria/gi,"bagno maria").replace(/becher/gi,"becker").replace(/capsula/gi,"caapsula").replace(/idrossido/gi,"idròssido").replace(/aspirala/gi,
"aspiralà"))}var c=new SpeechSynthesisUtterance(a);c.voice=VoiceHandle;c.volume=1;c.pitch=VOICE_PITCH;c.rate=VOICE_RATE;c.onstart=function(){VoiceRecEnable(!1)};c.onend=function(){VoiceRecEnable(!0);b&&b()};DEBUG&&console.log(LOG_PROMPT,'Voice synthesis "'+a+'"');Voice.cancel();Voice.speak(c);break;case VOICE_TYPE_PICOSERVER:a=new Audio(encodeURI(PicoTtsURI+a));a.onplay=function(){VoiceRecEnable(!1)};a.onended=function(){VoiceRecEnable(!0);b&&b()};a.play();break;case VOICE_TYPE_RESPONSIVE:responsiveVoice.isPlaying()||
(Prefs.VoiceActive?(DEBUG&&console.log(LOG_PROMPT,'Voice synthesis "'+a+'"'),responsiveVoice.speak(a,Msg.ResponsiveVoice,{onstart:function(){VoiceRecEnable(!1)},onend:function(){VoiceRecEnable(!0);b&&b()}})):b&&b())}}function StopSound(a){Scene.querySelector("#"+a).components.sound.stopSound()}function SubNums(a){for(var b="",c=0;c<a.length;c++){var e=a.charCodeAt(c),d=a[c-1];b=48<=e&&57>=e&&" "!=d&&"."!=d&&("0">d||"9"<d)?b+String.fromCharCode(e+8272):b+a[c]}return b}
function TexPrint(a,b,c,e,d){c=void 0===c?84:c;e=void 0===e?48:e;d=void 0===d?!1:d;a="string"==typeof a?document.querySelector("#"+a):a;var h=a.getContext("2d");h.fillStyle=d?"#FFFFFF00":"white";h.fillRect(0,0,a.width,a.height);h.fillStyle="#000";h.font=e+"px sans-serif";h.textAlign="center";h.fillText(b,a.width/2,c)}function VoiceRecEnable(a){Prefs.SpeechRecAvail&&Prefs.SpeechRecActive&&(a?annyang.start():annyang.abort())}
function WaitAnimEnd(a){return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){return 1==b.nextAddress?b.yield(Sleep(a),3):AnimRunning?b.yield(Sleep(50),3):b.jumpTo(0)})}function GlassLiquid(a){if(a.Water)return!0;a=$jscomp.makeIterator(a.ReaAdspect);for(var b=a.next();!b.done;b=a.next())if(b.value===ADSPECT_LIQUID)return!0;return!1};
